### ISSUE TITLE
Installing rails admin on a mounatble plugin

### ISSUE THREAD

**Issue by tabdulradi** [sferik/rails_admin#1412]
I am installing rails admin on a mountable plugin rather than regular app
I created the plugin using

``` bash
$rails plugin new my_cpanel --mountable
```

then added the requirements in the Gemfile, ran bundle successfully 
When I come the generate step, I get this error

``` bash
$rails g rails_admin:install
/usr/local/lib/ruby/gems/1.9.1/gems/rails_admin-0.0.5/lib/generators/rails_admin/install_generator.rb:20:in `install': undefined method `join' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `map'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/group.rb:238:in `dispatch'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/generators.rb:171:in `invoke'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.2.9/lib/rails/engine/commands.rb:21:in `<top (required)>'
    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from script/rails:8:in `<main>'
```

And here is my gemfile 

``` ruby
source "http://rubygems.org"

# Declare your gem's dependencies in cpanel.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'google-analytics-rails'
gem 'smt_rails', git: 'git://github.com/railsware/smt_rails.git'
gem 'rails_admin', '0.0.5'
gem 'devise', '2.1.2'
# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
```

Thanks in advance

**Comment by mshibuya** [comment]
Sorry I have no plan to provide support for this, I recommend installing manually.
