### ISSUE TITLE
Validation for has_many through.

### ISSUE THREAD

**Issue by zeroed** [sferik/rails_admin#1854]
Validation for has_many through.

My question is related to this particular line: https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/actions/edit.rb#L29

My situation involves 2 models plus one for the join table.
The model for the join table includes a validation check.

What I want is validates the relation between `Licence` and `LicenceType`.

```ruby
class Licence < ActiveRecord::Base

  has_many :licence_type_licences
  has_many :licence_types, through: :licence_type_licences

  #...
end
```

The _join table_ model:

```ruby
class LicenceTypeLicence < ActiveRecord::Base
  belongs_to :licence
  belongs_to :licence_type

  validate :check_pair_source_role

private
  def check_pair_source_role
    # ...
  end
end
```

Here the stack trace when I try to make an edit that should results in a validation failure:

```
ActiveRecord::RecordInvalid - Validation Failed: ........ :
  activerecord (3.2.15) lib/active_record/validations.rb:56:in `save!'
  activerecord (3.2.15) lib/active_record/attribute_methods/dirty.rb:33:in `save!'

  // ....

  activerecord (3.2.15) lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
  rails_admin (0.4.9) lib/rails_admin/adapters/active_record/abstract_object.rb:19:in `set_attributes'
  rails_admin (0.4.9) lib/rails_admin/config/actions/edit.rb:29:in `block (2 levels) in <class:Edit>'
  (eval):8:in `edit'
```

Updating my model Licence raise (correctly) an exception, but rails_admin doesn't handle it... `set_attributes` try to save my _join table model_.
How can I have a more graceful behaviour?

Thanks!

**Comment by zeroed** [comment]
:moyai: 

This is ... so old.
