### ISSUE TITLE
NameError in RailsAdmin::Main#dashboard

### ISSUE THREAD

**Issue by hmaruchi** [sferik/rails_admin#1909]
Hi,all.
I use this rails_admin and I'm getting this error in case of show the dashboard. 

I use the standard view interface of this gem, I don't create any kind of custom view&controller in my application.
I have tried this gem:rails_admin over three months, I don't have any kind of trouble at all.

I tried rails: 4.0.1/4.0.2 and rails_admin: 0.6.0/0.6.1, but I got same error.
And I tried to solve the cause of this error, but I give up because it is too difficult for me.
Please help me!

```
Showing /var/myappl/vendor/src/gems/rails_admin/app/views/layouts/rails_admin/application.html.haml where line #17 raised:

undefined local variable or method `dashboard_path' for #<#<Class:0x007fe921093cd0>:0x007fe9242f2e88>

14  .navbar.navbar-fixed-top
15    .navbar-inner
16      .container-fluid
17        %a.brand.pjax{:href => dashboard_path}
18          = _get_plugin_name[0] || 'Rails'
19          %small= _get_plugin_name[1] || 'Admin'
20        .nav-collapse
```

my environments as follow:

config/routes.rb:

``` ruby
MyAppl::Application.routes.draw do
  mount RailsAdmin::Engine=>'/system/monitors/admin/index', as: 'rails_admin'
    ...
  root to: 'appl/pages#index'
end
```

basic environments:

```
Ruby version    2.1.0 (x86_64-linux)
RubyGems version    2.2.0
Rack version    1.5
Rails version   4.0.2
JavaScript Runtime  Node.js (V8)
Action Pack version 4.0.2
Action Mailer version   4.0.2
Active Support version  4.0.2
Middleware  

    Rack::Sendfile
    ActionDispatch::Static
    Rack::Lock
    Dragonfly::CookieMonster
    Rack::Runtime
    Rack::MethodOverride
    ActionDispatch::RequestId
    Rails::Rack::Logger
    ActionDispatch::ShowExceptions
    ActionDispatch::DebugExceptions
    ActionDispatch::RemoteIp
    ActionDispatch::Reloader
    ActionDispatch::Callbacks
    ActionDispatch::Cookies
    ActionDispatch::Session::CookieStore
    ActionDispatch::Flash
    ActionDispatch::ParamsParser
    Remotipart::Middleware
    Rack::Head
    Rack::ConditionalGet
    Rack::ETag
    TreasureData::Logger::Agent::Rack::Hook
    Rack::Mongoid::Middleware::IdentityMap
    HttpAcceptLanguage::Middleware
    Dragonfly::Middleware
    Rack::Pjax

Application root    /var/myappl
Environment development
```

Gemfile file:

```
source 'https://rubygems.org'

gem 'rails', '4.0.2'
group :doc do
  gem 'sdoc', require: false
end
gem 'debugger', group: [:development, :test]
group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'yard', require: false
  gem 'spring'
  gem "spring-commands-rspec"
end
gem 'unicorn'
gem "mongoid_rails4", "~> 4.0.0"
gem "mongo", "~> 1.9.2"
gem 'bson', "~> 1.9.2"
gem "bson_ext", "~> 1.9.2"
gem 'protected_attributes'
gem 'fluentd'
gem 'td-logger'
gem "sunspot_rails", "~>2.0.0.pre.120925"
group :development do
  gem "sunspot_solr", "~>2.0.0.pre.120925"
end
gem 'sunspot_mongoid', path: 'vendor/src/gems/sunspot_mongoid'
gem 'rack-cache', require: 'rack/cache'
gem 'dragonfly'
gem 'dragonfly-mongo_data_store'
gem "redis"
gem 'sidekiq'
gem 'sidetiq'
gem 'sinatra', require: nil
gem 'slim'
gem 'systemu'
gem 'mimemagic'
gem 'jbuilder'
gem 'nokogiri'
gem 'sanitize'
gem 'rails_admin', "0.6.1"
gem 'oauth', "~> 0.4.4"
gem 'oauth2', "~> 0.8.0"
gem 'bcrypt-ruby', "~> 3.0.0"
gem 'state_machine'
gem 'monetize'
gem 'money-rails'
gem 'wunderground'
gem 'rails-i18n'
gem 'http_accept_language'
gem 'activemerchant'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'haml'
gem 'kaminari'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'bootstrap-sass'
gem 'bootstrap-datepicker-rails'
```

**Comment by matisoffn** [comment]
+1 having the same problem.

**Comment by cmfoster** [comment]
+1 on the same issue

**Comment by matisoffn** [comment]
please reopen

**Comment by mshibuya** [comment]
@matisoffn Please try [@scarfacedeb's suggestion](https://github.com/sferik/rails_admin/issues/1909#issuecomment-34789840) and report the result.

**Comment by kanyonbollinger** [comment]
I'm having this issue as well

**Comment by yamilelias** [comment]
This is what prints rails console in my application:

```
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `block in require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:236:in `load_dependency'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-3.2.9/lib/active_support/dependencies.rb:251:in `require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.6-x86-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.6-x86-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `each'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:72:in `block in require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `each'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler/runtime.rb:61:in `require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.7.7/lib/bundler.rb:133:in `require'
	from C:/Users/shama_000/Google Drive/Projects/Ruby Projects/Rails/dummy_app-master/config/application.rb:11:in `<top (required)>'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3.2.9/lib/rails/commands.rb:39:in `require'
	from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/railties-3.2.9/lib/rails/commands.rb:39:in `<top (required)>'
	from C:/Users/shama_000/Google Drive/Projects/Ruby Projects/Rails/dummy_app-master/script/rails:6:in `require'
	from C:/Users/shama_000/Google Drive/Projects/Ruby Projects/Rails/dummy_app-master/script/rails:6:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by najeebt** [comment]
Also seeing this one. "rake routes" output is good and shows the same rails_admin routes as in @hmaruchi's case, but line 8 in views/layouts/rails_admin/_navigation.html.haml throws a 

`undefined local variable or method `dashboard_path' for #<#<Class:0x007fa70fef6e98>:0x007fa711570480>`

**Comment by najeebt** [comment]
Ok, figured out a little more here. It looks like my tests are trying to render rails_admin layouts without ever instantiating the MainController. Since MainController is never loaded/instantiated, a bunch of important actions/paths that the layouts need are never defined by the main class_eval that dynamically defines all of MainControllers actions at line 13 in app/controllers/main_controller.rb. Does this provide more insight?

**Comment by mshibuya** [comment]
Please reopen if this is still an issue.
