### ISSUE TITLE
`layout :get_layout` problems

### ISSUE THREAD

**Issue by KamilLelonek** [sferik/rails_admin#1996]
```
ActionController::RoutingError (undefined method `layout' for RailsAdmin::MainController:Class):
  rails_admin (0.6.2) app/controllers/rails_admin/main_controller.rb:7:in `<class:MainController>'
  rails_admin (0.6.2) app/controllers/rails_admin/main_controller.rb:2:in `<module:RailsAdmin>'
  rails_admin (0.6.2) app/controllers/rails_admin/main_controller.rb:1:in `<top (required)>'
  activesupport (4.1.1) lib/active_support/dependencies.rb:443:in `load'
  activesupport (4.1.1) lib/active_support/dependencies.rb:443:in `block in load_file'
  activesupport (4.1.1) lib/active_support/dependencies.rb:633:in `new_constants_in'
  activesupport (4.1.1) lib/active_support/dependencies.rb:442:in `load_file'
  activesupport (4.1.1) lib/active_support/dependencies.rb:342:in `require_or_load'
  activesupport (4.1.1) lib/active_support/dependencies.rb:480:in `load_missing_constant'
  activesupport (4.1.1) lib/active_support/dependencies.rb:180:in `const_missing'
  activesupport (4.1.1) lib/active_support/inflector/methods.rb:240:in `const_get'
  activesupport (4.1.1) lib/active_support/inflector/methods.rb:240:in `block in constantize'
  activesupport (4.1.1) lib/active_support/inflector/methods.rb:236:in `each'
  activesupport (4.1.1) lib/active_support/inflector/methods.rb:236:in `inject'
  activesupport (4.1.1) lib/active_support/inflector/methods.rb:236:in `constantize'
  activesupport (4.1.1) lib/active_support/dependencies.rb:552:in `get'
  activesupport (4.1.1) lib/active_support/dependencies.rb:583:in `constantize'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:76:in `controller_reference'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:66:in `controller'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:44:in `call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  rack-pjax (0.7.0) lib/rack/pjax.rb:12:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/error_collector.rb:55:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/agent_hooks.rb:32:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/developer_mode.rb:45:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  rack-cors (0.2.9) lib/rack/cors.rb:54:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  activerecord (4.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.1) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/static.rb:64:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  puma (2.8.2) lib/puma/server.rb:490:in `handle_request'
  puma (2.8.2) lib/puma/server.rb:361:in `process_client'
  puma (2.8.2) lib/puma/server.rb:254:in `block in run'
  puma (2.8.2) lib/puma/thread_pool.rb:92:in `call'
  puma (2.8.2) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by nkeyes** [comment]
You have to include `ActionView::Layouts` (among other things) in ` ApplicationController`

```Ruby
class ApplicationController < ActionController::API
  include ActionView::Layouts
  include ActionController::ImplicitRender
  include ActionController::Helpers

  include ActionController::RequestForgeryProtection

  helper ApplicationHelper
end

**Comment by matstc** [comment]
Thanks for the hint @nkeyes. I had the same problem and the following worked for me:

```ruby
class ApplicationController < ActionController::API
  include ::ActionController::Flash
  include ::ActionView::Layouts
  include ::ActionController::Helpers
  include ::ActionController::MimeResponds
  include ::ActionController::RequestForgeryProtection
end
```

**Comment by mshibuya** [comment]
The same solution in #2172 will also work.
