### ISSUE TITLE
undefined method `email' for #<User> after upgrading to rails_admin 0.6.7

### ISSUE THREAD

**Issue by webandtech** [sferik/rails_admin#2221]
I have an application with a users table that does not have an email attribute. As of 0.6.7 navigating to rails admin causes the following exception. The issue is not present in versions below 0.6.7.

```
  active_model/attribute_methods.rb:433:in `method_missing'
    match ? attribute_missing(match, *args, &block) : super
  rails_admin/application_helper.rb:37:in `edit_user_link'
    link_to _current_user.email, url_for(action: edit_action.action_name, model_name: abstract_model.to_param, id: _current_user.id, controller: 'rails_admin/main')
  bundle/ruby/2.2.0/gems/rails_admin-0.6.7/app/views/layouts/rails_admin/_secondary_navigation.html.haml:7:in `_vendor_bundle_ruby_______gems_rails_admin_______app_views_layouts_rails_admin__secondary_navigation_html_haml___3226483290756962591_70185940238280'
    - if user_link = edit_user_link
  action_view/template.rb:145:in `block in render'
    view.send(method_name, locals, buffer, &block)
  active_support/notifications.rb:164:in `block in instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_support/notifications.rb:164:in `instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  action_view/template.rb:333:in `instrument'
    ActiveSupport::Notifications.instrument("#{action}.action_view", payload, &block)
  action_view/template.rb:143:in `render'
    instrument("!render_template") do
  action_view/renderer/partial_renderer.rb:339:in `render_partial'
    content = @template.render(view, locals) do |*name|
  action_view/renderer/partial_renderer.rb:310:in `block in render'
    render_partial
  action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
    ActiveSupport::Notifications.instrument("render_#{name}.action_view", options){ yield }
  active_support/notifications.rb:164:in `block in instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_support/notifications.rb:164:in `instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  action_view/renderer/abstract_renderer.rb:39:in `instrument'
    ActiveSupport::Notifications.instrument("render_#{name}.action_view", options){ yield }
  action_view/renderer/partial_renderer.rb:309:in `render'
    instrument(:partial, :identifier => identifier) do
  action_view/renderer/renderer.rb:47:in `render_partial'
    PartialRenderer.new(@lookup_context).render(context, options, block)
  action_view/renderer/renderer.rb:21:in `render'
    render_partial(context, options)
  action_view/helpers/rendering_helper.rb:32:in `render'
    view_renderer.render(self, options)
  haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
    return non_haml { render_without_haml(*args, &block) }
  haml/helpers.rb:89:in `non_haml'
    yield
  haml/helpers/action_view_mods.rb:10:in `render_with_haml'
    return non_haml { render_without_haml(*args, &block) }
  bundle/ruby/2.2.0/gems/rails_admin-0.6.7/app/views/layouts/rails_admin/_navigation.html.haml:7:in `_vendor_bundle_ruby_______gems_rails_admin_______app_views_layouts_rails_admin__navigation_html_haml__2998366685607054345_70185940448000'
    = render partial: 'layouts/rails_admin/secondary_navigation'
  action_view/template.rb:145:in `block in render'
    view.send(method_name, locals, buffer, &block)
  active_support/notifications.rb:164:in `block in instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_support/notifications.rb:164:in `instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  action_view/template.rb:333:in `instrument'
    ActiveSupport::Notifications.instrument("#{action}.action_view", payload, &block)
  action_view/template.rb:143:in `render'
    instrument("!render_template") do
  action_view/renderer/partial_renderer.rb:339:in `render_partial'
    content = @template.render(view, locals) do |*name|
  action_view/renderer/partial_renderer.rb:310:in `block in render'
    render_partial
```

**Comment by pearce89** [comment]
I have the same error at 0.6.7
