### ISSUE TITLE
column_types method not found

### ISSUE THREAD

**Issue by ericgross** [sferik/rails_admin#2238]
I am running the latest version of active_admin & rails (and postgres).

When trying to view the index for a model, I am getting this error:

```
Exception: ActionView::Template::Error: undefined method `column_types' for "User":String
--
 0: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/association.rb:107:in `association_key_type'
 1: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/association.rb:103:in `key_conversion_required?'
 2: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/association.rb:60:in `owners_by_key'
 3: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/association.rb:78:in `associated_records_by_owner'
 4: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/singular_association.rb:9:in `preload'
 5: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader/association.rb:20:in `run'
 6: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:137:in `block (2 levels) in preloaders_for_one'
 7: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:135:in `each'
 8: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:135:in `map'
 9: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:135:in `block in preloaders_for_one'
10: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:134:in `each'
11: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:134:in `flat_map'
12: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:134:in `preloaders_for_one'
13: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:106:in `preloaders_on'
14: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:94:in `block in preload'
15: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:93:in `each'
16: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:93:in `flat_map'
17: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/associations/preloader.rb:93:in `preload'
18: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:617:in `block in exec_queries'
19: /home/eric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:616:in `each'
```

**Comment by mshibuya** [comment]
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/rails-admin) for the support request, thanks.
