### ISSUE TITLE
can't convert Fixnum to Array (Fixnum#to_a gives Unitwise::Measurement)

### ISSUE THREAD

**Issue by cs0511** [sferik/rails_admin#2269]
I have two model User and Weight

And Weight reference user_id whose type is integer. 

When I want to edit a record of Weight. I got the error:

```
can't convert Fixnum to Array (Fixnum#to_a gives Unitwise::Measurement)

```

When track the code, I found it was caused by:

```
 [39, nil].map do |r|
          Array(r).map { |item| item.to_s }
        end
```
39 is the user_id. 

Actually Array(39) will get error. But Array('39') is fine.

How should I do with this? Is it a bug from your side?

```
Completed 500 Internal Server Error in 74ms

TypeError - can't convert Fixnum to Array (Fixnum#to_a gives Unitwise::Measurement):
  actionview (4.1.1) lib/action_view/helpers/form_options_helper.rb:356:in `block in options_for_select'
  actionview (4.1.1) lib/action_view/helpers/form_options_helper.rb:355:in `options_for_select'
  actionview (4.1.1) lib/action_view/helpers/tags/select.rb:23:in `render'
  actionview (4.1.1) lib/action_view/helpers/form_options_helper.rb:165:in `select'
  actionview (4.1.1) lib/action_view/helpers/form_options_helper.rb:779:in `select'
  rails_admin (0.6.7) app/views/rails_admin/main/_form_filtering_select.html.haml:29:in `___sers_chensong__rvm_gems_ruby_______phase_body_gems_rails_admin_______app_views_rails_admin_main__form_filtering_select_html_haml___2689013405143166768_2232567080'
  actionview (4.1.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.1) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.1) lib/action_view/template.rb:143:in `render'
  actionview (4.1.1) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
  actionview (4.1.1) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
  actionview (4.1.1) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.1) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.1) lib/action_view/renderer/partial_renderer.rb:278:in `render'
  actionview (4.1.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.1.1) lib/action_view/renderer/renderer.rb:21:in `render'
  actionview (4.1.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:89:in `non_haml'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  rails_admin (0.6.7) lib/rails_admin/config/fields/base.rb:217:in `block in <class:Base>'
  rails_admin (0.6.7) lib/rails_admin/config/configurable.rb:66:in `block in register_instance_option'
  rails_admin (0.6.7) lib/rails_admin/config/proxyable/proxy.rb:29:in `method_missing'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:69:in `field_for'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:51:in `block in input_for'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.1.1) lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:50:in `input_for'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:39:in `block in field_wrapper_for'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.1.1) lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:37:in `field_wrapper_for'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:28:in `block (2 levels) in fieldset_for'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:28:in `block in fieldset_for'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.1.1) lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:69:in `content_tag_with_haml'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:24:in `fieldset_for'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:16:in `block (2 levels) in generate'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:15:in `block in generate'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:128:in `without_field_error_proc_added_div'
  rails_admin (0.6.7) app/helpers/rails_admin/form_builder.rb:7:in `generate'
  rails_admin (0.6.7) app/views/rails_admin/main/edit.html.haml:2:in `block in ___sers_chensong__rvm_gems_ruby_______phase_body_gems_rails_admin_______app_views_rails_admin_main_edit_html_haml__3040000297285379024_2170098780'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:278:in `with_tabs'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.1.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.1.1) lib/action_view/helpers/form_helper.rb:434:in `form_for'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
  haml (4.0.6) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
  rails_admin (0.6.7) app/helpers/rails_admin/main_helper.rb:7:in `rails_admin_form_for'
  rails_admin (0.6.7) app/views/rails_admin/main/edit.html.haml:1:in `___sers_chensong__rvm_gems_ruby_______phase_body_gems_rails_admin_______app_views_rails_admin_main_edit_html_haml__3040000297285379024_2170098780'
  actionview (4.1.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.1) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.1) lib/action_view/template.rb:143:in `render'
  actionview (4.1.1) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  actionview (4.1.1) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `instrument'
  actionview (4.1.1) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionview (4.1.1) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  actionview (4.1.1) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  actionview (4.1.1) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
  actionview (4.1.1) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionview (4.1.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.1.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.1.1) lib/action_view/rendering.rb:99:in `_render_template'
  actionpack (4.1.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.1.1) lib/action_view/rendering.rb:82:in `render_to_body'
  actionpack (4.1.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.1.1) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  actionpack (4.1.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.1.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.1.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
   () Users/chensong/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.1.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.1.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:40:in `render'
  remotipart (1.2.1) lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  rails_admin (0.6.7) lib/rails_admin/config/actions/edit.rb:20:in `block (4 levels) in <class:Edit>'
  actionpack (4.1.1) lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
  rails_admin (0.6.7) lib/rails_admin/config/actions/edit.rb:19:in `block (2 levels) in <class:Edit>'
  rails_admin (0.6.7) app/controllers/rails_admin/main_controller.rb:22:in `edit'
  actionpack (4.1.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.1) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.1) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.1) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.1) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.1) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.1) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.1) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.1.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.1) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/flash.rb:254:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.1.1) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.1.1) lib/active_record/migration.rb:380:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.1) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.1.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/static.rb:64:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/application.rb:144:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by mshibuya** [comment]
Where does that piece of code come from?
Can you paste full stack trace?

**Comment by cs0511** [comment]
Hi mshibuya, @mshibuya 

Thank you so much for quick answer. I add the error message. Please check

**Comment by cs0511** [comment]
I didn't see any other have such issues. Did I miss any thing? @mshibuya

**Comment by mshibuya** [comment]
Ah, I think [unitwise](https://github.com/joshwlewis/unitwise) gem is to be blame.
That's swallowing `to_a` method call [here](https://github.com/joshwlewis/unitwise/blob/master/lib/unitwise/ext/numeric.rb#L22) and returning `Unitwise::Measurement` object, which is unexpected result for `to_a`(Array is expected, of course).

My advice is to stop using unitwise gem. That king of patching to existing class is a bad manner.
If you really need to use it, please consult with unitwise author on how to resolve this.

**Comment by cs0511** [comment]
@mshibuya   Very appreciate your comments. That's really helpful!
