### ISSUE TITLE
error with PaperTrail

### ISSUE THREAD

**Issue by CrimsonGlory** [sferik/rails_admin#2405]
Hi. I tried to add PaperTrail to my app following [this instructions](https://github.com/sferik/rails_admin/wiki/Papertrail)
Now when I log in to rails_admin I get this error
```
web_1 | PG::UndefinedTable: ERROR:  relation "version_associations" does not exist
web_1 | LINE 5:                WHERE a.attrelid = '"version_associations"'::...
web_1 |                                           ^
web_1 | :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
web_1 |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
web_1 |                 FROM pg_attribute a LEFT JOIN pg_attrdef d
web_1 |                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
web_1 |                WHERE a.attrelid = '"version_associations"'::regclass
web_1 |                  AND a.attnum > 0 AND NOT a.attisdropped
web_1 |                ORDER BY a.attnum
web_1 |
web_1 | Completed 500 Internal Server Error in 873ms (ActiveRecord: 55.3ms)
web_1 |
web_1 | ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "version_associations" does not exist
web_1 | LINE 5:                WHERE a.attrelid = '"version_associations"'::...
web_1 |                                           ^
web_1 | :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
web_1 |                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
web_1 |                 FROM pg_attribute a LEFT JOIN pg_attrdef d
web_1 |                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
web_1 |                WHERE a.attrelid = '"version_associations"'::regclass
web_1 |                  AND a.attnum > 0 AND NOT a.attisdropped
web_1 |                ORDER BY a.attnum
web_1 | ):
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
web_1 |   activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
web_1 |   activerecord (4.2.1) lib/active_record/attributes.rb:93:in `columns'
web_1 |   activerecord (4.2.1) lib/active_record/model_schema.rb:260:in `column_names'
web_1 |   activerecord (4.2.1) lib/active_record/relation/calculations.rb:226:in `aggregate_column'
web_1 |   activerecord (4.2.1) lib/active_record/relation/calculations.rb:252:in `execute_simple_calculation'
web_1 |   activerecord (4.2.1) lib/active_record/relation/calculations.rb:221:in `perform_calculation'
web_1 |   activerecord (4.2.1) lib/active_record/relation/calculations.rb:127:in `calculate'
web_1 |   activerecord (4.2.1) lib/active_record/relation/calculations.rb:42:in `count'
web_1 |   rails_admin (0.6.8) lib/rails_admin/adapters/active_record.rb:43:in `count'
web_1 |   rails_admin (0.6.8) lib/rails_admin/config/actions/dashboard.rb:26:in `block (3 levels) in <class:Dashboard>'
web_1 |   rails_admin (0.6.8) lib/rails_admin/config/actions/dashboard.rb:24:in `each'
web_1 |   rails_admin (0.6.8) lib/rails_admin/config/actions/dashboard.rb:24:in `block (2 levels) in <class:Dashboard>'
web_1 |   rails_admin (0.6.8) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
web_1 |   rails_admin (0.6.8) app/controllers/rails_admin/main_controller.rb:22:in `dashboard'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
web_1 |   actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
web_1 |   actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
web_1 |   actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
web_1 |   activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
web_1 |   activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
web_1 |   activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
web_1 |   activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
web_1 |   actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
web_1 |   actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
web_1 |   actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
web_1 |   actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
web_1 |   actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
web_1 |   railties (4.2.1) lib/rails/engine.rb:518:in `call'
web_1 |   railties (4.2.1) lib/rails/railtie.rb:194:in `public_send'
web_1 |   railties (4.2.1) lib/rails/railtie.rb:194:in `method_missing'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
web_1 |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
web_1 |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
web_1 |   rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
web_1 |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
web_1 |   warden (1.2.3) lib/warden/manager.rb:34:in `catch'
web_1 |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
web_1 |   rack (1.6.1) lib/rack/etag.rb:24:in `call'
web_1 |   rack (1.6.1) lib/rack/conditionalget.rb:25:in `call'
web_1 |   rack (1.6.1) lib/rack/head.rb:13:in `call'
web_1 |   remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
web_1 |   rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
web_1 |   rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
web_1 |   activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
web_1 |   activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
web_1 |   activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
web_1 |   activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
web_1 |   railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
web_1 |   railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
web_1 |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
web_1 |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
web_1 |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
web_1 |   railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
web_1 |   request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
web_1 |   rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
web_1 |   rack (1.6.1) lib/rack/runtime.rb:18:in `call'
web_1 |   activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
web_1 |   rack (1.6.1) lib/rack/lock.rb:17:in `call'
web_1 |   actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
web_1 |   rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
web_1 |   railties (4.2.1) lib/rails/engine.rb:518:in `call'
web_1 |   railties (4.2.1) lib/rails/application.rb:164:in `call'
web_1 |   rack (1.6.1) lib/rack/lock.rb:17:in `call'
web_1 |   rack (1.6.1) lib/rack/content_length.rb:15:in `call'
web_1 |   rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
web_1 |   /usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
web_1 |   /usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
web_1 |   /usr/local/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```
I added PaperTrail by inserting this line into Gemfile
```
gem 'paper_trail', '~> 4.0.0'
```
I ```bundle install``` and ```bundle exec rails generate paper_trail:install --with-changes  ```
The migrations where run successfully
I do have the versions table
```
postgres=# \d versions
                                       Table "public.versions"
     Column     |            Type             |                       Modifiers                       
----------------+-----------------------------+-------------------------------------------------------
 id             | integer                     | not null default nextval('versions_id_seq'::regclass)
 item_type      | character varying           | not null
 item_id        | integer                     | not null
 event          | character varying           | not null
 whodunnit      | character varying           | 
 object         | text                        | 
 created_at     | timestamp without time zone | 
 object_changes | text                        | 
Indexes:
    "versions_pkey" PRIMARY KEY, btree (id)
    "index_versions_on_item_type_and_item_id" btree (item_type, item_id)
``` 
and PaperTrail seems to be working
```
[3] pry(main)> Provider.first.versions.count
  Provider Load (1.5ms)  SELECT  "providers".* FROM "providers"  ORDER BY "providers"."id" ASC LIMIT 1
   (1.4ms)  SELECT COUNT(*) FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2  [["item_id", 3], ["item_type", "Provider"]]
=> 2

```
Yes, I added the line 
```
config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0
```
Versions of everything:
```
 rails_admin (0.6.8)
 rails (4.2.1)
paper_trail (4.0.0)
# ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```
And I did restart the application several times.
My paper_trail configuration is minimal. Is just the next line on one class (Provider).
```
has_paper_trail :only => [:credit]
```
I'm out of ideas.
Any ideas?
Thanks in advance

**Comment by hut8** [comment]
You need to do this:
`rails g paper_trail:install --with-associations`

You have the `versions` table, but you also need `version_associations`

**Comment by hut8** [comment]
I feel like this should be better documented. I'm not sure why rails_admin actually requires that `version_associations` be enabled. I get this error even without using

`config.audit_with :paper_trail #...`

anywhere in my initializer. I'm looking into why this is happening now.

**Comment by hut8** [comment]
Alright now it's documented in the Wiki.

**Comment by CrimsonGlory** [comment]
Thanks!
