### ISSUE TITLE
has_and_belongs_to_many causes ActiveRecord::UnknownPrimaryKey on save

### ISSUE THREAD

**Issue by dgobaud** [sferik/rails_admin#2424]
Using rails_admin 0.7.0 and rails 4.2.4

I have an Address model with has_and_belongs_to_many :shifts. The join table was created without a primary key as the rails documentation says must be done

    create_table :addresses_shifts, id: false do |t|
      t.integer :address_id, :index => true
      t.integer :shift_id, :index => true
    end

    add_index :addresses_shifts, [:address_id, :shift_id], :unique => true

when editing the address and adding a Shift by moving it from the left box to the right box and clicking save I get this error

Unknown primary key for table addresses_shifts in model Address::HABTM_Shifts.

ActiveRecord::UnknownPrimaryKey (Unknown primary key for table addresses_shifts in model Address::HABTM_Shifts.):
  activerecord (4.2.4) lib/active_record/reflection.rb:571:in `primary_key'
  activerecord (4.2.4) lib/active_record/reflection.rb:319:in `active_record_primary_key'
  activerecord (4.2.4) lib/active_record/reflection.rb:153:in `join_keys'
  activerecord (4.2.4) lib/active_record/associations/association_scope.rb:99:in `last_chain_scope'
  activerecord (4.2.4) lib/active_record/associations/association_scope.rb:139:in `add_constraints'
  activerecord (4.2.4) lib/active_record/associations/association_scope.rb:39:in `scope'
  activerecord (4.2.4) lib/active_record/associations/association_scope.rb:5:in `scope'
  activerecord (4.2.4) lib/active_record/associations/association.rb:97:in `association_scope'
  activerecord (4.2.4) lib/active_record/associations/association.rb:86:in `scope'
  activerecord (4.2.4) lib/active_record/associations/collection_association.rb:423:in `scope'
  activerecord (4.2.4) lib/active_record/associations/collection_proxy.rb:37:in `initialize'
  activerecord (4.2.4) lib/active_record/relation/delegation.rb:106:in `new'
  activerecord (4.2.4) lib/active_record/relation/delegation.rb:106:in `create'
  activerecord (4.2.4) lib/active_record/associations/collection_association.rb:41:in `reader'
  activerecord (4.2.4) lib/active_record/associations/builder/association.rb:115:in `versions'
  paper_trail (4.0.0.rc1) lib/paper_trail/has_paper_trail.rb:202:in `clear_rolled_back_versions'
  activesupport (4.2.4) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.4) lib/active_support/callbacks.rb:263:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:263:in `block in simple'
  activesupport (4.2.4) lib/active_support/callbacks.rb:506:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:506:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:506:in `each'
  activesupport (4.2.4) lib/active_support/callbacks.rb:506:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_rollback_callbacks'
  activerecord (4.2.4) lib/active_record/transactions.rb:322:in `rolledback!'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/transaction.rb:69:in `rollback_records'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/transaction.rb:147:in `rollback'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/transaction.rb:186:in `rescue in within_new_transaction'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.4) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.4) lib/active_record/associations/collection_association.rb:182:in `transaction'
  activerecord (4.2.4) lib/active_record/associations/collection_association.rb:373:in `replace'
  activerecord (4.2.4) lib/active_record/associations/collection_association.rb:67:in `ids_writer'
  activerecord (4.2.4) lib/active_record/associations/builder/collection_association.rb:76:in `shift_ids='
  activerecord (4.2.4) lib/active_record/attribute_assignment.rb:54:in `public_send'
  activerecord (4.2.4) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
  activerecord (4.2.4) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
  actionpack (4.2.4) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  actionpack (4.2.4) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  activerecord (4.2.4) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
  rails_admin (0.7.0) lib/rails_admin/adapters/active_record/abstract_object.rb:19:in `set_attributes'
  rails_admin (0.7.0) lib/rails_admin/config/actions/edit.rb:27:in `block (2 levels) in <class:Edit>'
  rails_admin (0.7.0) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
  rails_admin (0.7.0) app/controllers/rails_admin/main_controller.rb:22:in `edit'
  actionpack (4.2.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.4) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.4) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.4) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.4) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.4) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.4) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.11.2) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.2) lib/puma/server.rb:375:in `process_client'
  puma (2.11.2) lib/puma/server.rb:262:in `block in run'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by dgobaud** [comment]
turns out the problem is papertrail!
