### ISSUE TITLE
Assumptions that the English locale is available

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#2432]
There are a couple of assumptions here and there that the English locale is available.

This causes rails admin to fail (at least: 0.6.8, 0.7.0, master branch) in DateTime fields

Eg:

application.rb

``` rb
    config.i18n.default_locale = :it
    config.i18n.available_locales = %i(it)
```

``` rb
# Schema
create_table "players", force: :cascade do |t|
  t.string   "name"
  t.datetime "birthday"
end

# Player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true
end

# Rails admin config
config.model Player do
  field :name
  field :birthday
end
```

Open rails admin, click on the model on the left sidebar, it will fail here:

https://github.com/sferik/rails_admin/blob/50d6e59bc8bf3515c84c78d874af66e6440fec5c/lib/rails_admin/config/fields/types/datetime.rb#L32

`I18n::InvalidLocale in RailsAdmin::Main#index`

**Comment by tagliala** [comment]
Any news here?

Are you able to confirm this?

**Comment by tagliala** [comment]
spec/rails_admin/config/fields/types/datetime_spec.rb
```rb
    it 'handles non-English applications' do
      begin
        old_available_locales = I18n.available_locales
        old_default_locale = I18n.default_locale
        old_locale = I18n.locale
        I18n.available_locales = [:it]
        I18n.default_locale = :it
        I18n.locale = :it

        RailsAdmin.config(FieldTest) do |_config|
          field :datetime_field do
            default_value DateTime.parse('01/01/2012')
          end
        end

        field = RailsAdmin.config(FieldTest).fields.detect do |f|
          f.name == :datetime_field
        end.with(object: FieldTest.new)

        expect(field.formatted_value).to eq 'January 01, 2012 00:00'
      ensure
        I18n.available_locales = old_available_locales
        I18n.default_locale = old_default_locale
        I18n.locale = old_locale
      end
    end
```

```sh
Failures:

  1) RailsAdmin::Config::Fields::Types::Datetime#formatted_value handles non-English applications
     Failure/Error: fallback = ::I18n.t(date_format, scope: i18n_scope, locale: :en)
     
     I18n::InvalidLocale:
       :en is not a valid locale
     # /Users/geremia/.rvm/gems/ruby-2.2.3/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
     # /Users/geremia/.rvm/gems/ruby-2.2.3/gems/i18n-0.7.0/lib/i18n.rb:151:in `translate'
     # ./lib/rails_admin/config/fields/types/datetime.rb:41:in `block in <class:Datetime>'
     # ./lib/rails_admin/config/configurable.rb:66:in `instance_eval'
     # ./lib/rails_admin/config/configurable.rb:66:in `block in register_instance_option'
     # ./lib/rails_admin/config/fields/types/datetime.rb:65:in `block in <class:Datetime>'
     # ./lib/rails_admin/config/configurable.rb:66:in `instance_eval'
     # ./lib/rails_admin/config/configurable.rb:66:in `block in register_instance_option'
     # ./lib/rails_admin/config/proxyable/proxy.rb:27:in `method_missing'
     # ./spec/rails_admin/config/fields/types/datetime_spec.rb:48:in `block (3 levels) in <top (required)>'
```

PS: any better way to stub calls to I18n?

**Comment by mshibuya** [comment]
Fixed by https://github.com/sferik/rails_admin/commit/4f555cc2a673dcf886bbfb3a77c73022f895a18a.
