### ISSUE TITLE
rails_admin crashes frequently

### ISSUE THREAD

**Issue by erithair** [sferik/rails_admin#2434]
This hasn't happened before for months until yesterday, on my production server the rails_admin suddenly crashed several times and received this error: 

```
I, [2015-10-14T01:53:49.409981 #27094]  INFO -- : Started GET "/admin" for 199.48.228.111 at 2015-10-14 01:53:49 +0000
I, [2015-10-14T01:53:49.414945 #27094]  INFO -- : Processing by RailsAdmin::MainController#dashboard as HTML
I, [2015-10-14T01:53:49.417216 #27094]  INFO -- : Completed 500 Internal Server Error in 2ms
ArgumentError (wrong number of arguments (0 for 1..3)):
  facets (3.0.0) lib/core/facets/kernel/with.rb:16:in `instance_eval'
  facets (3.0.0) lib/core/facets/kernel/with.rb:16:in `with'
  rails_admin (0.7.0) app/controllers/rails_admin/main_controller.rb:18:in `dashboard'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
```

The full stacktrace is in this gist: https://gist.github.com/erithair/ff82345394b024c2c79f

These very frequent crashes are causing us considerable issues. Would appreciate any help in solving it. Much thanks.

**Comment by mshibuya** [comment]
Fixed now, thanks!
