### ISSUE TITLE
rails_admin 0.8.0 fails to precompile

### ISSUE THREAD

**Issue by wli** [sferik/rails_admin#2486]
Running: `bundle exec rake assets:precompile` fails in `rails_admin` `0.8.0`.

```
rake aborted!
Sprockets::FileNotFound: couldn't find file 'rails_admin/moment-with-locales'
  (in /home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/rails_admin-0.8.0/app/assets/javascripts/rails_admin/rails_admin.js:7)
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:106:in `resolve'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:146:in `require_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:167:in `block in process_directives'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:165:in `each'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:165:in `process_directives'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/directive_processor.rb:99:in `evaluate'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:16:in `initialize'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `new'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:377:in `build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/ubuntu/myproject/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.2.3@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by PikachuEXE** [comment]
It is also missing file `rails_admin/bootstrap-datetimepicker-build`

**Comment by mshibuya** [comment]
Dup of #2481.
