### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$btn-primary-bg" with RA 0.8.1

### ISSUE THREAD

**Issue by fmh** [sferik/rails_admin#2501]
cannot precompile with capistrano to my prod server 

````ruby
rake stdout: Nothing written
rake stderr: rake aborted!
Sass::SyntaxError: Undefined variable: "$btn-primary-bg".
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/rails_admin-0.8.1/vendor/assets/stylesheets/rails_admin/_bootstrap-datetimepicker.scss:8
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/script/tree/variable.rb:49:in `_perform'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:469:in `visit_variable'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `map'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:157:in `visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:8:in `visit'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/root_node.rb:36:in `css_tree'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/tree/root_node.rb:20:in `render'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-3.4.19/lib/sass/engine.rb:278:in `render'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sass-rails-5.0.4/lib/sass/rails/template.rb:47:in `evaluate'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:60:in `block in load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:44:in `load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:47:in `yield'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/bundle.rb:23:in `block in call'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/utils.rb:183:in `dfs'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/bundle.rb:24:in `call'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:60:in `block in load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/loader.rb:44:in `load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:47:in `yield'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/base.rb:66:in `find_asset'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/manifest.rb:134:in `block in find'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/manifest.rb:133:in `each'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/manifest.rb:133:in `find'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/sprockets/manifest.rb:168:in `compile'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-3.5.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/rails/apps/polyapp/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
** Invoke deploy:failed (first_time)
** Execute deploy:failed
````

**Comment by bbenezech** [comment]
Check compilation order. Remove all bulky imports of `*.css` that could include rails_admin asset files.
