### ISSUE TITLE
Specs failing on master branch with rails 4.2

### ISSUE THREAD

**Issue by tagliala** [sferik/rails_admin#2510]
I think this is a sprockets 3.0.0 related failure

```sh
$ appraisal rails-4.2 rspec ./spec/integration/rails_admin_spec.rb
Run options: exclude {:mongoid=>true, :skip_active_record=>true}

Randomized with seed 56366
............FF.

Failures:

  1) RailsAdmin html head loads javascript files in body
     Failure/Error: is_expected.to have_selector('head script[src^="/assets/rails_admin/rails_admin.js"]', visible: false)
       expected #has_selector?("head script[src^=\"/assets/rails_admin/rails_admin.js\"]", {:visible=>false}) to return true, got false
     # ./spec/integration/rails_admin_spec.rb:38:in `block (3 levels) in <top (required)>'

  2) RailsAdmin html head loads stylesheets in header
     Failure/Error: is_expected.to have_selector('head link[href^="/assets/rails_admin/rails_admin.css"]', visible: false)
       expected #has_selector?("head link[href^=\"/assets/rails_admin/rails_admin.css\"]", {:visible=>false}) to return true, got false
     # ./spec/integration/rails_admin_spec.rb:34:in `block (3 levels) in <top (required)>'

```

Issue is due to the hashed value:
```html
<link rel="stylesheet" media="all" href="/assets/rails_admin/rails_admin-726a0e3d0e6d969e238202ac66a1b95d762d442ded813bdbec5798921424c1ac.css" />
<script src="/assets/rails_admin/rails_admin-884cfbe74f506962ae47fb15b865c9996a5ebe2e051942605a29bd9d830a9437.js"></script>
```

Let me know if you need more info or help

**Comment by tagliala** [comment]
:+1:

**Comment by SuperMasterBlasterLaser** [comment]
@mshibuya one test gives this error:

     rspec ./spec/integration/rails_admin_spec.rb:127 # RailsAdmin secondary navigation does not show Gravatar when user doesn't have email method

Is it connected to this problem?
