### ISSUE TITLE
undefined method `collect' for nil:NilClass in csv_converter.rb:77

### ISSUE THREAD

**Issue by etagwerker** [sferik/rails_admin#2593]
Hello, 

I'm currently experiencing an issue when trying to export the CSV for a set of bulk ids from a subscope of my main model. 

```
NoMethodError (undefined method `collect' for nil:NilClass):
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/support/csv_converter.rb:77:in `generate_csv_header'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/support/csv_converter.rb:68:in `block in generate_csv_string'
  /Users/etagwerker/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/csv.rb:1157:in `generate'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/support/csv_converter.rb:67:in `generate_csv_string'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/support/csv_converter.rb:38:in `to_csv'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/config/actions/index.rb:76:in `block (4 levels) in <class:Index>'
  actionpack (4.1.14.2) lib/action_controller/metal/mime_responds.rb:258:in `call'
  actionpack (4.1.14.2) lib/action_controller/metal/mime_responds.rb:258:in `respond_to'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/config/actions/index.rb:43:in `block (2 levels) in <class:Index>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) app/controllers/rails_admin/main_controller.rb:22:in `index'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) lib/rails_admin/config/actions/export.rb:21:in `block (2 levels) in <class:Export>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@loli/bundlerrails_admin (355dc80f8a20) app/controllers/rails_admin/main_controller.rb:22:in `export'
  actionpack (4.1.14.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.14.2) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.14.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.14.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.14.2) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.14.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.14.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.14.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.14.2) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.14.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.14.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.14.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.14.2) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
  railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
  railties (4.1.14.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.14.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.14.2) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/routing/route_set.rb:690:in `call'
  rack-pjax (0.8.0) lib/rack/pjax.rb:12:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.14.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.14.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.14.2) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.14.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.14.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.14.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.14.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.14.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.14.2) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.1.14.2) lib/rails/engine.rb:514:in `call'
  railties (4.1.14.2) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `call'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

After some debugging, it seems that `@objects` is initially right but then it is getting overwritten by the index action. 

Later, when it tries to use `objects` to create the `CSVConverter` object, it finds that `objects` is blank and it fails. 

I've experienced a similar issue in version `0.8.1` - That's why I tried `master` at 355dc80.

I've found a potential solution to this problem. 

I'll submit a PR in a few minutes.

Thanks!

**Comment by bricesanchez** [comment]
I've the same problem on a custom export but your PR does not fix my error.

**Comment by etagwerker** [comment]
@bricesanchez Yeah, I noticed that this solution is not appropriate. I'm currently working on improving it.

**Comment by bricesanchez** [comment]
My error was related to a malformed Model scope, the master branch rails_admin code works for me.

**Comment by etagwerker** [comment]
After further review, I decided to change my patch (#2594) - Now it seems to work fine. 

The problem I had was that I had this: 

```ruby
  config.model Order do
    weight -1
    list do
      scopes [:single_box_type, :subscription_box_type]
    end
    ...
```

But when I tried to export items from the second scope `:subscription_box_type` the bulk action wouldn't work. It would try to filter the selected items (`:subscription_box_type`) with the first scope (`:single_box_type`)

Then it would find no records and that would cause the exception.

**Comment by Quintasan** [comment]
I found a simple way to reproduce it - go to any model. Uncheck `Select all fields` and try exporting to CSV

**Comment by Quintasan** [comment]
@etagwerker Would you happen to have ANY idea how could I even solve this? I even tried monkey patching RailsAdmin to `raise RailsAdmin::ObjectNotFound` hoping it would redirect me to the dashboard but it doesn't capture it's own Exceptions for some reason.

**Comment by mshibuya** [comment]
`@objects` should be unrelated, this will be the same issue as #1685.
