### ISSUE TITLE
 undefined method `config' for RailsAdmin:Module (NoMethodError)

### ISSUE THREAD

**Issue by CHILL99** [sferik/rails_admin#2714]
Hi!

During ` rspec spec`got next error

```
/home/ch99/Projects/staffr-backend/config/initializers/rails_admin.rb:3:in `<top (required)>': undefined method `config' for RailsAdmin:Module (NoMethodError)
Did you mean?  concerning
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/engine.rb:615:in `each'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/ch99/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /home/ch99/Projects/staffr-backend/config/environment.rb:5:in `<top (required)>'
	from /home/ch99/Projects/staffr-backend/spec/rails_helper.rb:4:in `require'
	from /home/ch99/Projects/staffr-backend/spec/rails_helper.rb:4:in `<top (required)>'
	from /home/ch99/Projects/staffr-backend/spec/controllers/setup_controller_spec.rb:1:in `require'
	from /home/ch99/Projects/staffr-backend/spec/controllers/setup_controller_spec.rb:1:in `<top (required)>'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/ch99/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /home/ch99/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
	from /home/ch99/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
	from /home/ch99/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/ch99/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

config:

```
RailsAdmin.config do |config|

  require Rails.root.join('lib', 'rails_admin.rb')

  ### Popular gems integration

  # == Devise ==
  config.authenticate_with do
    warden.authenticate! scope: :admin
  end
  config.current_user_method(&:current_admin)

  ## == Cancan ==
  # config.authorize_with :cancan

  ## == PaperTrail ==
  # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  config.parent_controller = 'BaseApplicationController'

  config.included_models = %w[BadgeImage Company Public::RegistrationRequest]

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    statistics
    new_company
    new
    export
    bulk_delete
    show
    edit
    delete
    show_in_app

    ## With an audit adapter, you can add:
    # history_index
    # history_show
  end
end
```

spec_helper:
```
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
   # RailsAdmin path helpers
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.

  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  #   - http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
  #   - http://www.teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   - http://myronmars.to/n/dev-blog/2014/05/notable-changes-in-rspec-3#new__config_option_to_disable_rspeccore_monkey_patching
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end
  config.before(:each) do
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

```
   rails_admin (1.0.0.rc)
      builder (~> 3.1)
      coffee-rails (~> 4.0)
      font-awesome-rails (>= 3.0, < 5)
      haml (~> 4.0)
      jquery-rails (>= 3.0, < 5)
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.14)
      nested_form (~> 0.3)
      rack-pjax (>= 0.7)
      rails (>= 4.0, < 6)
      remotipart (~> 1.0)
      sass-rails (>= 4.0, < 6)
```

**Comment by mshibuya** [comment]
Make sure that RailsAdmin is loaded before `config/initializers/rails_admin.rb`. Pasting your `Gemfile` might help detecting issue.

**Comment by JulienCorb** [comment]
@mshibuya I'm having the exact same issue. How can I make sure RailsAdmin is loaded before `config/initializers/rails_admin.rb` ?
