### ISSUE TITLE
ArgumentError in RailsAdmin::Main#new

### ISSUE THREAD

**Issue by npendery** [sferik/rails_admin#2729]
Getting this error in only one model, all other ones work fine

```
ActionView::Template::Error (too few arguments):
     8:     selected_id = selected.send(field.associated_primary_key)
     9:     selected_name = selected.send(field.associated_object_label_method)
    10:   else
    11:     selected_id = field.selected_id
    12:     selected_name = field.formatted_value
    13:   end
    14:
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/lib/rails_admin/config/fields/association.rb:101:in `format'
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/lib/rails_admin/config/fields/association.rb:101:in `value'
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/lib/rails_admin/config/fields/types/belongs_to_association.rb:11:in `block in <class:BelongsToAssociation>'
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/lib/rails_admin/config/configurable.rb:66:in `instance_eval'
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/lib/rails_admin/config/configurable.rb:66:in `block in register_instance_option'
/Users/nickpendery/.gem/ruby/2.3.1/bundler/gems/rails_admin-b92a4d1a30b7/app/views/rails_admin/main/_form_filtering_select.html.haml:11:in `___sers_nickpendery__gem_ruby_______bundler_gems_rails_admin_b__a_d_a__b__app_views_rails_admin_main__form_filtering_select_html_haml___3092901664861921410_70297635148140'
```

**Comment by dai199** [comment]
I also faced the same error. But that was a model name problem.
For me, this problem happened when model name is "test".
So I changed this model to another name and problem was solved.

I don't know your problem well, but think about one of solutions.
