### ISSUE TITLE
Could not catch CanCan::AccessDenied using rescue_from in application_controller in rails-5-api

### ISSUE THREAD

**Issue by zekedran** [sferik/rails_admin#2742]
added rescue_from in application_controller.rb

```
class ApplicationController < ActionController::API
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end
```

and still getting 500 Internal Server due to uncaught exception. However `rescue_from` gets to catch exceptions thrown from other resources.

```
{"status":500,"error":"Internal Server Error","exception":"#\u003cCanCan::AccessDenied: You are not authorized to access this page.\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"cancancan (1.15.0) lib/cancan/ability.rb:216:in `authorize!'"},{"id":1,"trace":"rails_admin (1.0.0) lib/rails_admin/extensions/cancancan/authorization_adapter.rb:11:in `initialize'"},{"id":2,"trace":"rails_admin (1.0.0) lib/rails_admin/config.rb:153:in `new'"},{"id":3,"trace":"rails_admin (1.0.0) lib/rails_admin/config.rb:153:in `block in authorize_with'"},{"id":4,"trace":"rails_admin (1.0.0) app/controllers/rails_admin/application_controller.rb:52:in `instance_eval'"},{"id":5,"trace":"rails_admin (1.0.0) app/controllers/rails_admin/application_controller.rb:52:in `_authorize!'"},{"id":6,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'"},{"id":7,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `call'"},{"id":8,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'"},{"id":9,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `call'"},{"id":10,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in \u003cmodule:Callbacks\u003e'"},{"id":11,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `call'"},{"id":12,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'"},{"id":13,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'"},{"id":14,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'"},{"id":15,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `each'"},{"id":16,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'"},{"id":17,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":18,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":19,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":20,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":21,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":22,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":23,"trace":"activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":24,"trace":"activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":25,"trace":"activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":26,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":27,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":28,"trace":"activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":29,"trace":"actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":30,"trace":"actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'"},{"id":31,"trace":"actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":32,"trace":"actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":33,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":34,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":35,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":36,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":37,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":38,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":39,"trace":"railties (5.0.0.1) lib/rails/engine.rb:522:in `call'"},{"id":40,"trace":"railties (5.0.0.1) lib/rails/railtie.rb:193:in `public_send'"},{"id":41,"trace":"railties (5.0.0.1) lib/rails/railtie.rb:193:in `method_missing'"},{"id":42,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in \u003cclass:Constraints\u003e'"},{"id":43,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `call'"},{"id":44,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'"},{"id":45,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":46,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":47,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":48,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":49,"trace":"rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'"},{"id":50,"trace":"rack (2.0.1) lib/rack/method_override.rb:22:in `call'"},{"id":51,"trace":"remotipart (1.3.0) lib/remotipart/middleware.rb:32:in `call'"},{"id":52,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":53,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'"},{"id":54,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":55,"trace":"activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'"},{"id":56,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":57,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":58,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":59,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":60,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":61,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":62,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":63,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":64,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":65,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":66,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":67,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'"},{"id":68,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":69,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'"},{"id":70,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":71,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":72,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":73,"trace":"activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":74,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":75,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":76,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":77,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":78,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":79,"trace":"railties (5.0.0.1) lib/rails/engine.rb:522:in `call'"},{"id":80,"trace":"puma (3.6.0) lib/puma/configuration.rb:225:in `call'"},{"id":81,"trace":"puma (3.6.0) lib/puma/server.rb:578:in `handle_request'"},{"id":82,"trace":"puma (3.6.0) lib/puma/server.rb:415:in `process_client'"},{"id":83,"trace":"puma (3.6.0) lib/puma/server.rb:275:in `block in run'"},{"id":84,"trace":"puma (3.6.0) lib/puma/thread_pool.rb:116:in `call'"},{"id":85,"trace":"puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"cancancan (1.15.0) lib/cancan/ability.rb:216:in `authorize!'"},{"id":1,"trace":"rails_admin (1.0.0) lib/rails_admin/extensions/cancancan/authorization_adapter.rb:11:in `initialize'"},{"id":2,"trace":"rails_admin (1.0.0) lib/rails_admin/config.rb:153:in `new'"},{"id":3,"trace":"rails_admin (1.0.0) lib/rails_admin/config.rb:153:in `block in authorize_with'"},{"id":4,"trace":"rails_admin (1.0.0) app/controllers/rails_admin/application_controller.rb:52:in `instance_eval'"},{"id":5,"trace":"rails_admin (1.0.0) app/controllers/rails_admin/application_controller.rb:52:in `_authorize!'"},{"id":6,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'"},{"id":7,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `call'"},{"id":8,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'"},{"id":9,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `call'"},{"id":10,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in \u003cmodule:Callbacks\u003e'"},{"id":11,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `call'"},{"id":12,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'"},{"id":13,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'"},{"id":14,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'"},{"id":15,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `each'"},{"id":16,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'"},{"id":17,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":18,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":19,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":20,"trace":"actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":21,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":22,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":23,"trace":"activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":24,"trace":"activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":25,"trace":"activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":26,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":27,"trace":"actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":28,"trace":"activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":29,"trace":"actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":30,"trace":"actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'"},{"id":31,"trace":"actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":32,"trace":"actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":33,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":34,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":35,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":36,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":37,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":38,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":39,"trace":"railties (5.0.0.1) lib/rails/engine.rb:522:in `call'"},{"id":40,"trace":"railties (5.0.0.1) lib/rails/railtie.rb:193:in `public_send'"},{"id":41,"trace":"railties (5.0.0.1) lib/rails/railtie.rb:193:in `method_missing'"},{"id":42,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in \u003cclass:Constraints\u003e'"},{"id":43,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `call'"},{"id":44,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'"},{"id":45,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":46,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":47,"trace":"actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":48,"trace":"actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":49,"trace":"rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'"},{"id":50,"trace":"rack (2.0.1) lib/rack/method_override.rb:22:in `call'"},{"id":51,"trace":"remotipart (1.3.0) lib/remotipart/middleware.rb:32:in `call'"},{"id":52,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":53,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'"},{"id":54,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":55,"trace":"activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'"},{"id":56,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":57,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":58,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":59,"trace":"activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":60,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":61,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":62,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":63,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":64,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":65,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":66,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":67,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'"},{"id":68,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":69,"trace":"activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'"},{"id":70,"trace":"railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":71,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":72,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":73,"trace":"activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":74,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":75,"trace":"actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":76,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":77,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":78,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":79,"trace":"railties (5.0.0.1) lib/rails/engine.rb:522:in `call'"},{"id":80,"trace":"puma (3.6.0) lib/puma/configuration.rb:225:in `call'"},{"id":81,"trace":"puma (3.6.0) lib/puma/server.rb:578:in `handle_request'"},{"id":82,"trace":"puma (3.6.0) lib/puma/server.rb:415:in `process_client'"},{"id":83,"trace":"puma (3.6.0) lib/puma/server.rb:275:in `block in run'"},{"id":84,"trace":"puma (3.6.0) lib/puma/thread_pool.rb:116:in `call'"},{"id":85,"trace":"puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'"}]}}
```

**Comment by hexinpeter** [comment]
Add the following config line in `initialisers/rails_admin.rb`

    config.parent_controller = 'ApplicationController'

**Comment by zekedran** [comment]
it throws this exception with a 404 response

    ActionController::RoutingError: undefined method `helper_method' for RailsAdmin::ApplicationController:Class

**Comment by lareb** [comment]
Works for me . thanks @hexinpeter

**Comment by juampi** [comment]
@hexinpeter's solution works. However, the [Wik](https://github.com/sferik/rails_admin/wiki/CanCanCan#handle-unauthorized-access)i didn't mention that necessary step. I updated it accordingly.

**Comment by vanmart** [comment]
this solution must be on rails-admin documentation lika a instalation TIP!
