### ISSUE TITLE
ExecJS::RuntimeError: SyntaxError: Unexpected token punc «,», expected punc «:» (line: 38633, col: 30, pos: 1142049)

### ISSUE THREAD

**Issue by Kosai106** [sferik/rails_admin#2749]
I recently started getting an odd issue when deploying to production, and it seems to be rails_admin related.

``` bash
RAILS_ENV=production bundle exec rake assets:precompile --trace

** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
autoprefixer: /Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:202:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
autoprefixer: /Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:231:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
autoprefixer: /Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:270:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
autoprefixer: /Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:1483:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
autoprefixer: /Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rails_admin-0.8.1/app/assets/stylesheets/rails_admin/rails_admin.scss.erb:1593:3: Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
I, [2016-10-25T17:20:18.725500 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-47d977c5a39d895f0c2f313356bed821f1f1908d66d2f9d67a518ca01b4bc05c.css
I, [2016-10-25T17:20:18.737170 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-47d977c5a39d895f0c2f313356bed821f1f1908d66d2f9d67a518ca01b4bc05c.css.gz
I, [2016-10-25T17:20:18.739027 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/bg_fallback-69fe09a001b1a5db2ea587c5ad86945184ca6d0768c6d8a78e744a5f2ba1d5fd.png
I, [2016-10-25T17:20:18.742256 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/ui-icons_222222_256x240-ee747f0c248c797a4184589cb9921c9eae3e8a9982af90d7d1554949e72ba398.png
I, [2016-10-25T17:20:18.756807 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/ui-icons_454545_256x240-5d0cf948d7765488899a06be518f8885ef572725e6d8a9733eab7e6b746fce11.png
I, [2016-10-25T17:20:18.759735 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/icon_sprite-34a30806fcba43a2effc9739cb7a370a865199a7d38bfcbc7c2474ef3ff70ded.png
I, [2016-10-25T17:20:18.766667 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/slider_handles-c90007cd625a8a728d11b98eaf2dcef5578306f831c485244a3dd9fba3f5643c.png
I, [2016-10-25T17:20:18.767782 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/aristo/images/progress_bar-a2ed712d76dcffc7a06918cd389511bca2cf7bb91c12b1d865bf44c7b2c46289.gif
I, [2016-10-25T17:20:18.769008 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/multiselect/icon_sprite-34a30806fcba43a2effc9739cb7a370a865199a7d38bfcbc7c2474ef3ff70ded.png
I, [2016-10-25T17:20:18.770322 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-n-light-e7daf3169259a9fd6b8177b8e89ff2b964cd3dababd580a46d7fb4eecc07763b.png
I, [2016-10-25T17:20:18.772494 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-n-dark-3e5b4d04bfb41e949bf382d5c8796a57e820be71cbcf2a617e3d7cd082096b64.png
I, [2016-10-25T17:20:18.774202 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-s-light-19a2c581a24251e690ef20f702ed8ba36fd48f244f87512b8bcfecb486c9a04f.png
I, [2016-10-25T17:20:18.775615 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/multiselect/ui-icon-circle-triangle-s-dark-23d5d567f5aa864475d96c07d6f5f1d4da4271ea7033f49438f4c05a74759424.png
I, [2016-10-25T17:20:18.777958 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/select2-8ddf680d1a86d603653e43f694bbb6dc1010aa81f5c0c9c87181e10e064e503b.png
I, [2016-10-25T17:20:18.780322 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_background-94008c06d9c175f1ef2a50ecb47cb7c962e84f4b5f0e1cb093616925c58cb973.png
I, [2016-10-25T17:20:18.782662 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/colorpicker_overlay-e2ca63c25eaada26c255cf0561ba5041081d43735f990291c40b9fe93306c62b.png
I, [2016-10-25T17:20:18.785335 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/colorpicker_select-980ae86d6aab751f6f67a1191d78c0fa54b533583456b905ec43b34d5806ee2d.gif
I, [2016-10-25T17:20:18.787388 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_indic-855f25240c8d3b60ecdf276eaea891a3325ed64d9a80a8c77c1e82e1dd408fea.gif
I, [2016-10-25T17:20:18.790367 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_hex-1d4e85766443b6349adfc64d74f1ad65fba7aabf22e70dd0d09f1268ac66a4fa.png
I, [2016-10-25T17:20:18.791637 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_rgb_r-54289ccad89df00514d84ba6d16d1a0abc0d61de95dcfc054bf2202e238a7cb6.png
I, [2016-10-25T17:20:18.792967 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_rgb_g-8ab4d41c46fc26080b75eecc6f8c25d8f6db5264cf56ecc4993f86d100ebd71f.png
I, [2016-10-25T17:20:18.794875 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_rgb_b-22f2da1810cd9da18a1f93418b8f45bd3cb676aa9790ad5e1aba37779fb3ac31.png
I, [2016-10-25T17:20:18.796608 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_hsb_h-6e77fbf83a497dfd4ed3a12a1783edd9c8e38feac08bfbf469de89b75e3891aa.png
I, [2016-10-25T17:20:18.798654 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_hsb_s-6103d936e65bff097a72d04443a52428ecb6938909aa4c6a069f561303a8dc5d.png
I, [2016-10-25T17:20:18.803030 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_hsb_b-55152fc13f6cf9a7f21b30cf11acd09186e7f1e208d187086befb31bfa666b70.png
I, [2016-10-25T17:20:18.806322 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/colorpicker/custom_submit-5676ce2923afebd275c74baa8556fafde77085c59a4b2a76e50dc0195f388f19.png
I, [2016-10-25T17:20:18.807905 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot
I, [2016-10-25T17:20:18.906633 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot.gz
I, [2016-10-25T17:20:18.907288 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2
I, [2016-10-25T17:20:18.908939 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff
I, [2016-10-25T17:20:18.910507 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf
I, [2016-10-25T17:20:18.911391 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf.gz
I, [2016-10-25T17:20:18.912082 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg
I, [2016-10-25T17:20:18.914211 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
I, [2016-10-25T17:20:27.444518 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-cdd3fbcdcffafde3cd4ffcd7e0ff4a35c94e6308e959897f11d97fcf645f48ca.js
I, [2016-10-25T17:20:27.444962 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-cdd3fbcdcffafde3cd4ffcd7e0ff4a35c94e6308e959897f11d97fcf645f48ca.js.gz
I, [2016-10-25T17:20:27.445883 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-cdd3fbcdcffafde3cd4ffcd7e0ff4a35c94e6308e959897f11d97fcf645f48ca.js
I, [2016-10-25T17:20:27.446190 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/rails_admin-cdd3fbcdcffafde3cd4ffcd7e0ff4a35c94e6308e959897f11d97fcf645f48ca.js.gz
I, [2016-10-25T17:20:28.000593 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/jquery.colorpicker-53523840ff1c0eb62916b6dce79f11aba975e8e04df522191d1e7703eb235fb0.js
I, [2016-10-25T17:20:28.000826 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/jquery.colorpicker-53523840ff1c0eb62916b6dce79f11aba975e8e04df522191d1e7703eb235fb0.js.gz
I, [2016-10-25T17:20:28.919996 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/jquery.colorpicker-948429d2d71cda1ec511884b9acb61832b86e631e18567e9f25ae4839a447a24.css
I, [2016-10-25T17:20:28.920254 #43588]  INFO -- : Writing /Users/oesterkilde/Projects/findgoout/public/assets/rails_admin/jquery.colorpicker-948429d2d71cda1ec511884b9acb61832b86e631e18567e9f25ae4839a447a24.css.gz
rake aborted!
ExecJS::RuntimeError: SyntaxError: Unexpected token punc «,», expected punc «:» (line: 38633, col: 30, pos: 1142049)

Error
    at new JS_Parse_Error (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:11948)
    at js_error (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:12167)
    at croak (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:22038)
    at token_error (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:22175)
    at expect_token (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:22411)
    at expect (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:22562)
    at /private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:215
    at /private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:22954
    at expr_atom (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3623:30987)
    at maybe_unary (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:1752)
    at expr_ops (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:2523)
    at maybe_conditional (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:2615)
    at maybe_assign (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:3058)
    at expression (/private/var/folders/1s/50c9cngn6psct1xd9860_1hw0000gn/T/execjs20161025-43588-1bdgmtwjs:3624:3384)
new JS_Parse_Error ((execjs):3623:11948)
js_error ((execjs):3623:12167)
croak ((execjs):3623:22038)
token_error ((execjs):3623:22175)
expect_token ((execjs):3623:22411)
expect ((execjs):3623:22562)
(execjs):3624:215
(execjs):3623:22954
expr_atom ((execjs):3623:30987)
maybe_unary ((execjs):3624:1752)
expr_ops ((execjs):3624:2523)
maybe_conditional ((execjs):3624:2615)
maybe_assign ((execjs):3624:3058)
expression ((execjs):3624:3384)
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/uglifier-3.0.3/lib/uglifier.rb:182:in `run_uglifyjs'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/uglifier-3.0.3/lib/uglifier.rb:144:in `compile'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/uglifier_compressor.rb:52:in `call'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:142:in `block in find'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:209:in `each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:105:in `each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:104:in `each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:140:in `find'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-3.7.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/Users/oesterkilde/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/bin/rake:23:in `load'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/bin/rake:23:in `<main>'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/oesterkilde/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
```

Any ideas? I've been Googling for hours but I can't seem to fix it at all.

**Comment by mshibuya** [comment]
Try this and reopen if it's a problem with RailsAdmin.
http://stackoverflow.com/a/38605526
