### ISSUE TITLE
ActionView::Template::Error (Missing host to link to!.. in production with Rails 5

### ISSUE THREAD

**Issue by constantm** [sferik/rails_admin#2834]
I'm getting the following issue when running in production with Rails 5:

```
I, [2017-02-12T22:27:04.999132 #55644]  INFO -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] Completed 500 Internal Server Error in 579ms (ActiveRecord: 84.1ms)
F, [2017-02-12T22:27:05.001299 #55644] FATAL -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]
F, [2017-02-12T22:27:05.001476 #55644] FATAL -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
F, [2017-02-12T22:27:05.001843 #55644] FATAL -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     27:                 .progress-bar.animate-width-to{:class => "progress-bar-#{get_indicator(percent)}", :'data-animate-length' => ([1.0, percent].max.to_i * 20), :'data-animate-width-to' => "#{[2.0, percent].max.to_i}%", style: "width:2%"}
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     28:                   = @count[abstract_model.model.name]
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     29:             %td.links
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     30:               %ul.inline.list-inline= menu_for :collection, abstract_model, nil, true
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     31: - if @auditing_adapter && authorized?(:history_index)
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     32:   #block-tables.block
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]     33:     .content
F, [2017-02-12T22:27:05.001884 #55644] FATAL -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b]
F, [2017-02-12T22:27:05.002004 #55644] FATAL -- : [e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] actionpack (5.0.1) lib/action_dispatch/http/url.rb:62:in `full_url_for'
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] actionpack (5.0.1) lib/action_dispatch/http/url.rb:52:in `url_for'
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:303:in `block in <class:RouteSet>'
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:719:in `url_for'
[e474c8a9-71c8-4cd2-8fb9-f1cb4f59b24b] actionpack (5.0.1) lib/action_dispatch/routing/url_for.rb:172:in `url_for'
```

I've tried just about every way imaginable to set the host with no luck. This happens on master, as well as the newest published gem, with Ruby 2.4 as well as Ruby 2.3.1. When looking at the code, I see it's calling `rails_admin.url_for` instead of just `url_for`. Not sure if this is part of why it's ignoring any of my attempts to set the host. Looking at `RailsAdmin._routes.default_url_options`, the engine seems to have the host set correctly, but `rails_admin.url_for` is not using it.

I've been struggling with this for hours - can somebody please point me in the right direction?

**Comment by constantm** [comment]
Same issue as: https://github.com/rails/rails/issues/13372

Removing `include Rails.application.routes.url_helpers` from my `ApplicationMailer` fixed the issue.
