### ISSUE TITLE
Unable to save models with a ActiveRecord::Store

### ISSUE THREAD

**Issue by vedant1811** [sferik/rails_admin#2902]
I have a model with `store :data`:

    class Job < ActiveRecord::Base
      store :data,
            accessors: [
                :title, :description,
            ]
    end

When I try to create a new job from rails_admin, I get the error: `Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess`

I get the same error when I try to edit an existing object.

It was working fine in `v0.8.1` but I have upgraded to rails 5 and cannot revert back to it.

Additionally, if I remove the ` !ruby/hash:ActiveSupport::HashWithIndifferentAccess` in the data field the record is saved without any error, i.e.:

    --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    title: title
    description: desc

fails, but

    ---
    title: title
    description: desc

works.

Full trace:

    
    Psych::DisallowedClass in RailsAdmin::MainController#new
    Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess
    
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/class_loader.rb:97:in `find'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/class_loader.rb:28:in `load'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:396:in `resolve_class'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:281:in `visit_Psych_Nodes_Mapping'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
    /home/vedant/.rubies/ruby-2.4.1/lib/ruby/2.4.0/psych.rb:302:in `safe_load'
    rails_admin (1.2.0) lib/rails_admin.rb:49:in `yaml_load'
    rails_admin (1.2.0) lib/rails_admin/config/fields/types/serialized.rb:16:in `parse_value'
    rails_admin (1.2.0) lib/rails_admin/config/fields/types/serialized.rb:20:in `parse_input'
    rails_admin (1.2.0) lib/rails_admin/config/proxyable/proxy.rb:27:in `method_missing'
    rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:96:in `block in sanitize_params_for!'
    rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:96:in `each'
    rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:96:in `sanitize_params_for!'
    rails_admin (1.2.0) lib/rails_admin/config/actions/new.rb:36:in `block (2 levels) in <class:New>'
    rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
    rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:22:in `new'
    actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
    actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
    actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
    actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
    activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
    actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
    activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
    actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
    actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
    actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
    actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
    actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
    actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
    railties (5.1.2) lib/rails/engine.rb:522:in `call'
    railties (5.1.2) lib/rails/railtie.rb:185:in `public_send'
    railties (5.1.2) lib/rails/railtie.rb:185:in `method_missing'
    actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
    actionpack (5.1.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
    actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
    actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
    rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
    omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
    omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
    omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
    remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
    rack (2.0.3) lib/rack/etag.rb:25:in `call'
    rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
    rack (2.0.3) lib/rack/head.rb:12:in `call'
    rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
    rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
    activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
    actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
    web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
    web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
    web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
    railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
    activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
    activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
    railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
    sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
    rack (2.0.3) lib/rack/method_override.rb:22:in `call'
    rack (2.0.3) lib/rack/runtime.rb:22:in `call'
    activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
    rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
    sentry-raven (2.5.3) lib/raven/integrations/rack.rb:50:in `call'
    railties (5.1.2) lib/rails/engine.rb:522:in `call'
    puma (3.8.2) lib/puma/configuration.rb:224:in `call'
    puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
    puma (3.8.2) lib/puma/server.rb:435:in `process_client'
    puma (3.8.2) lib/puma/server.rb:299:in `block in run'
    puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by gee-forr** [comment]
I have the same issue, not with `ActiveRecord::Store`, but rather with storing jsonb data as a Hash in postgres.

@vedant1811 - were you able to find a fix? If so, please could you share?

**Comment by thegreyfellow** [comment]
I'm having the same issue when trying to load a hash with indifferent access:

`Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess`

any news on this issue?

**Comment by Kamal-buqileh** [comment]
any news on this issue?
