### ISSUE TITLE
 ActionView::Template::Error: undefined method `paginate' 

### ISSUE THREAD

**Issue by bastoune** [sferik/rails_admin#2939]
ActionView::Template::Error: undefined method `paginate` I can access to `MY_SITE/admin`

But when I click to see an entity list, I get a 500 Internal error with the flowing stack trace :

```
NoMethodError: undefined method `paginate' for #<#<Class:0x00000007069a80>:0x00000007034ec0>
  from bundle/ruby/2.3.0/gems/rails_admin-1.2.0/app/views/rails_admin/main/index.html.haml:109:in `block in _vendor_bundle_ruby_______gems_rails_admin_______app_views_rails_admin_main_index_html_haml__4449801334222553799_58695560'
  from haml/helpers/action_view_mods.rb:115:in `block (2 levels) in form_tag_with_haml'
  from haml/helpers.rb:292:in `with_tabs'
  from haml/helpers/action_view_mods.rb:115:in `block in form_tag_with_haml'
  from haml/helpers.rb:690:in `block in haml_bind_proc'
  from haml/helpers.rb:382:in `block in capture_haml'
  from haml/helpers.rb:667:in `with_haml_buffer'
  from haml/helpers.rb:378:in `capture_haml'
  from haml/helpers/xss_mods.rb:62:in `capture_haml_with_haml_xss'
  from haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
  from action_view/helpers/form_tag_helper.rb:70:in `form_tag'
  from haml/helpers/action_view_mods.rb:118:in `form_tag_with_haml'
  from haml/helpers/action_view_xss_mods.rb:19:in `form_tag_with_haml_xss'
  from bundle/ruby/2.3.0/gems/rails_admin-1.2.0/app/views/rails_admin/main/index.html.haml:69:in `_vendor_bundle_ruby_______gems_rails_admin_______app_views_rails_admin_main_index_html_haml__4449801334222553799_58695560'
  from action_view/template.rb:145:in `block in render'
  from active_support/notifications.rb:166:in `instrument'
  from action_view/template.rb:333:in `instrument'
  from action_view/template.rb:143:in `render'
  from action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  from action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_view/renderer/abstract_renderer.rb:39:in `instrument'
  from action_view/renderer/template_renderer.rb:53:in `block in render_template'
  from action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  from action_view/renderer/template_renderer.rb:52:in `render_template'
  from action_view/renderer/template_renderer.rb:14:in `render'
  from action_view/renderer/renderer.rb:46:in `render_template'
  from action_view/renderer/renderer.rb:27:in `render'
  from action_view/rendering.rb:100:in `_render_template'
  from action_controller/metal/streaming.rb:217:in `_render_template'
  from action_view/rendering.rb:83:in `render_to_body'
  from action_controller/metal/rendering.rb:32:in `render_to_body'
  from action_controller/metal/renderers.rb:37:in `render_to_body'
  from abstract_controller/rendering.rb:25:in `render'
  from action_controller/metal/rendering.rb:16:in `render'
  from action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  from active_support/core_ext/benchmark.rb:12:in `block in ms'
  from benchmark.rb:308:in `realtime'
  from active_support/core_ext/benchmark.rb:12:in `ms'
  from action_controller/metal/instrumentation.rb:44:in `block in render'
  from action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  from action_controller/metal/instrumentation.rb:43:in `render'
  from remotipart/render_overrides.rb:16:in `render_with_remotipart'
  from rails_admin/config/actions/index.rb:44:in `block (4 levels) in <class:Index>'
  from action_controller/metal/mime_responds.rb:217:in `respond_to'
  from rails_admin/config/actions/index.rb:42:in `block (2 levels) in <class:Index>'
  from rails_admin/main_controller.rb:22:in `instance_eval'
  from rails_admin/main_controller.rb:22:in `index'
  from action_controller/metal/implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:198:in `process_action'
  from action_controller/metal/rendering.rb:10:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:555:in `block (2 levels) in compile'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:92:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:29:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:250:in `process_action'
  from abstract_controller/base.rb:137:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:196:in `dispatch'
  from action_controller/metal/rack_delegation.rb:13:in `dispatch'
  from action_controller/metal.rb:237:in `block in action'
  from action_dispatch/routing/route_set.rb:74:in `dispatch'
  from action_dispatch/routing/route_set.rb:43:in `serve'
  from action_dispatch/journey/router.rb:43:in `block in serve'
  from action_dispatch/journey/router.rb:30:in `each'
  from action_dispatch/journey/router.rb:30:in `serve'
  from action_dispatch/routing/route_set.rb:817:in `call'
  from rails/engine.rb:518:in `call'
  from rails/railtie.rb:194:in `public_send'
  from rails/railtie.rb:194:in `method_missing'
  from action_dispatch/routing/mapper.rb:51:in `serve'
  from action_dispatch/journey/router.rb:43:in `block in serve'
  from action_dispatch/journey/router.rb:30:in `each'
  from action_dispatch/journey/router.rb:30:in `serve'
  from action_dispatch/routing/route_set.rb:817:in `call'
  from rack/pjax.rb:12:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from dragonfly/middleware.rb:14:in `call'
  from mongoid/query_cache.rb:104:in `block in call'
  from mongoid/query_cache.rb:69:in `cache'
  from mongoid/query_cache.rb:104:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:35:in `catch'
  from warden/manager.rb:35:in `call'
  from rack/etag.rb:24:in `call'
  from rack/conditionalget.rb:25:in `call'
  from rack/head.rb:13:in `call'
  from remotipart/middleware.rb:32:in `call'
  from action_dispatch/middleware/params_parser.rb:27:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from action_dispatch/middleware/cookies.rb:560:in `call'
  from action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from active_support/callbacks.rb:88:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_call_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:27:in `call'
  from action_dispatch/middleware/remote_ip.rb:78:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  from action_dispatch/middleware/show_exceptions.rb:30:in `call'
  from chewy/railtie.rb:17:in `block in call'
  from chewy/strategy.rb:63:in `wrap'
  from chewy.rb:187:in `strategy'
  from chewy/railtie.rb:17:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:20:in `block in call'
  from logstash-logger/tagged_logging.rb:5:in `block in tagged'
  from logstash-logger/tagged_logging.rb:16:in `tagged'
  from logstash-logger/tagged_logging.rb:5:in `tagged'
  from rails/rack/logger.rb:20:in `call'
  from request_store/middleware.rb:9:in `call'
  from action_dispatch/middleware/request_id.rb:21:in `call'
  from rack/methodoverride.rb:22:in `call'
  from dragonfly/cookie_monster.rb:9:in `call'
  from rack/contrib/runtime.rb:18:in `call'
  from rack/cors.rb:93:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from rails/engine.rb:518:in `call'
  from rails/application.rb:165:in `call'
  from rails/railtie.rb:194:in `public_send'
  from rails/railtie.rb:194:in `method_missing'
  from rack/tempfile_reaper.rb:15:in `call'
  from rack/lint.rb:49:in `_call'
  from rack/lint.rb:37:in `call'
  from rack/showexceptions.rb:24:in `call'
  from rack/commonlogger.rb:33:in `call'
  from sinatra/base.rb:219:in `call'
  from rack/chunked.rb:54:in `call'
  from rack/content_length.rb:15:in `call'
  from unicorn/http_server.rb:606:in `process_client'
  from unicorn/http_server.rb:702:in `worker_loop'
  from unicorn/http_server.rb:549:in `spawn_missing_workers'
  from unicorn/http_server.rb:142:in `start'
  from bundle/ruby/2.3.0/gems/unicorn-5.3.1/bin/unicorn:126:in `<top (required)>'
  from bundle/ruby/2.3.0/bin/unicorn:23:in `load'
  from bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:27:in `run'
  from bundler/cli.rb:365:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
  from bundler/cli.rb:22:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:444:in `start'
  from bundler/cli.rb:13:in `start'
  from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:121:in `with_friendly_errors'
  from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
  from /usr/local/bin/bundle:23:in `load'
  from /usr/local/bin/bundle:23:in `<main>'
```

Here is My packages verison list : 
```
actionmailer 4.2.10
actionpack 4.2.10
actionview 4.2.10
active_data	1.0.0
active_model_serializers 0.10.6
activejob 4.2.10
activemodel 4.2.10
activerecord 4.2.10
activesupport 4.2.10
addressable	2.5.2
api_pagination_headers	2.1.1
apitome 0.1.0
arel	
6.0.4
autoprefixer-rails	
7.1.4.1
avatar_magick	1.0.2
aws-sdk	2.10.57
aws-sdk-core	2.10.57
aws-sdk-resources	2.10.57
aws-sigv4	1.0.2
axlsx	2.1.0.pre
bcrypt	3.1.11
bcrypt-ruby	3.1.5
bson	3.2.7
bson_ext	1.5.1
builder	3.2.3
bundler	1.15.3
cancancan	2.0.0
case_transform 0.2
chewy 0.9.0
climate_control 0.2.0
cocaine 0.5.8
coffee-rails 4.0.1
coffee-script	2.4.1
coffee-script-source	1.12.2
color	1.8
commander 4.4.3
concurrent-ruby	1.0.5
connection_pool	2.2.1
crass	1.0.2
css_parser	1.6.0
dalli	2.7.6
devise	3.5.10
diff-lcs	1.3
domain_name 0.5.20170404
dragonfly	1.1.3
easy_diff	1.0.0
elasticsearch 5.0.4
elasticsearch-api 5.0.4
elasticsearch-transport 5.0.4
erubis	2.7.0
excon 0.59.0
execjs	2.7.0
faraday 0.13.1
fastimage	2.1.0
fission 0.5.0
fog	1.42.0
fog-aliyun 0.2.0
fog-atmos 0.1.0
fog-aws	1.4.1
fog-brightbox 0.13.0
fog-cloudatcost 0.1.2
fog-core	1.45.0
fog-digitalocean 0.3.0
fog-dnsimple	1.0.0
fog-dynect 0.0.3
fog-ecloud 0.3.0
fog-google 0.1.0
fog-internet-archive 0.0.1
fog-joyent 0.0.1
fog-json	1.0.2
fog-local 0.4.0
fog-openstack 0.1.21
fog-ovirt 0.1.1
fog-powerdns 0.1.1
fog-profitbricks 4.0.0
fog-rackspace 0.1.5
fog-radosgw 0.0.5
fog-riakcs 0.1.0
fog-sakuracloud	1.7.5
fog-serverlove 0.1.2
fog-softlayer	1.1.4
fog-storm_on_demand 0.1.1
fog-terremark 0.1.0
fog-vmfusion 0.1.0
fog-voxel 0.1.0
fog-vsphere	1.13.1
fog-xenserver 0.3.0
fog-xml 0.1.3
font-awesome-rails 4.7.0.2
formatador 0.2.5
gcm 0.1.1
glebtv_mongoid_userstamp 0.7.2
globalid 0.4.0
google-webfonts-rails 0.0.4
grim	1.3.3
haml 5.0.3
haml-rails	1.0.0
highline	1.7.8
hike	1.2.3
houston	2.2.4
html2haml	2.2.0
htmlentities 4.3.4
http-cookie	1.0.3
httparty 0.15.6
i18n 0.8.6
i18n-js	3.0.1
inflecto 0.0.2
intercom	3.5.17
ipaddress 0.8.3
jmespath	1.3.1
jquery-rails 4.3.1
jquery-ui-rails 5.0.5
json	2.1.0
jsonapi-renderer 0.1.3
kaminari 0.17.0
kaminari-core	1.0.1
kaminari-mongoid	1.0.1
kgio	2.11.0
kramdown	1.15.0
libv8	3.16.14.19
logstash-event	1.2.02
logstash-logger 0.25.1
loofah	2.1.1
macaddr	1.7.1
mail	2.6.6
memcachier 0.0.2
mime-types	3.1
mime-types-data	3.2016.0521
mimemagic 0.3.2
mini_magick 4.8.0
mini_portile2	2.3.0
minitest 5.10.3
mongoid 4.0.2
mongoid-audit	1.0.2
mongoid-compatibility 0.5.0
mongoid-history 0.4.7
mongoid-paperclip 0.0.11
mongoid-scroll 0.3.5
mongoid_orderable 5.1.0
mongoid_paranoia 0.2.1
mongoid_rails_migrations	1.1.0
mongoid_userstamp 0.4.0
moped	2.0.7
multi_json	1.12.2
multi_xml 0.6.0
multipart-post	2.0.0
mustache	1.0.5
nested_form 0.3.2
netrc 0.11.0
nokogiri	1.8.1
open_uri_redirections 0.2.1
optionable 0.2.0
origin	2.3.1
orm_adapter 0.5.0
paperclip 5.1.0
pdfkit 0.8.2
protected_attributes	1.1.4
public_suffix	3.0.0
rack	1.6.8
rack-contrib	1.7.0
rack-cors	1.0.1
rack-pjax	1.0.0
rack-protection	1.5.3
rack-test 0.6.3
rails 4.2.10
rails-api 0.4.1
rails-deprecated_sanitizer	1.0.3
rails-dom-testing	1.0.8
rails-html-sanitizer	1.0.3
rails-i18n 4.0.9
rails_admin	1.2.0
railties 4.2.10
raindrops 0.19.0
rake	12.1.0
rbovirt 0.1.4
rbvmomi	1.11.3
redis	3.3.5
redis-namespace	1.5.3
ref	2.0.0
remotipart	1.3.1
request_store	1.3.2
responders	2.4.0
rest-client	2.0.2
roadie	3.2.2
roadie-rails	1.2.1
rspec	3.1.0
rspec-core	3.1.7
rspec-expectations	3.1.2
rspec-mocks	3.1.3
rspec-support	3.1.2
rspec_api_documentation 5.1.0
ruby_parser	3.10.1
rubyzip	1.2.1
sass	3.2.19
sass-rails 4.0.5
sentry-raven	2.6.3
sexp_processor 4.10.0
sidekiq 5.0.5
simple_enum	2.3.0
sinatra	1.4.8
sprockets	2.12.4
sprockets-rails	2.3.3
systemu	2.6.5
temple 0.8.0
therubyracer 0.12.3
thor 0.20.0
thread_safe 0.3.6
tilt	1.4.1
timeliness 0.3.8
trollop	2.1.2
tzinfo	1.2.3
uglifier	3.2.0
unf 0.1.4
unf_ext 0.0.7.4
unicorn 5.3.1
uuid	2.3.8
validates_timeliness	3.0.15
warden	1.2.7
wisper	1.6.1
wisper-mongoid 0.1.0
wisper-sidekiq 0.0.1
wkhtmltopdf-binary 0.12.3.1
write_xlsx 0.85.1
xml-simple	1.1.5
zip-zip 0.3
```

**Comment by bastoune** [comment]
I solved this issue by also upgrading mongoid dependecies.

Apparently, Kaminari 1.0.1 is not compatible with `mongoid-audit 1.0.2`
