### ISSUE TITLE
Rails Admin 1.4.1 crashes app on boot (can't modify frozen Array)

### ISSUE THREAD

**Issue by vincentwoo** [sferik/rails_admin#3069]
Diff:

```
diff --git a/Gemfile.lock b/Gemfile.lock
index e6f70205..bb6953d6 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -206,7 +206,7 @@ GEM
       nokogiri (>= 1.5.9)
     mail (2.7.0)
       mini_mime (>= 0.1.1)
-    marcel (0.3.2)
+    marcel (0.3.3)
       mimemagic (~> 0.3.2)
     memoist (0.16.0)
     memory_profiler (0.9.11)
@@ -283,7 +283,7 @@ GEM
     rails_12factor (0.0.3)
       rails_serve_static_assets
       rails_stdout_logging
-    rails_admin (1.4.0)
+    rails_admin (1.4.1)
       builder (~> 3.1)
       coffee-rails (~> 4.0)
       font-awesome-rails (>= 3.0, < 5)
@@ -345,7 +345,7 @@ GEM
     rouge (3.2.0)
     ruby-saml (1.8.0)
       nokogiri (>= 1.5.10)
-    sass (3.5.7)
+    sass (3.6.0)
       sass-listen (~> 4.0.0)
     sass-listen (4.0.0)
       rb-fsevent (~> 0.9, >= 0.9.4)
```

App boot:

```
Traceback (most recent call last):
	32: from bin/rails:4:in `<main>'
	31: from bin/rails:4:in `require'
	30: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
	29: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
	28: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
	27: from /Users/vwoo/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	26: from /Users/vwoo/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	25: from /Users/vwoo/.gem/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	24: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:95:in `perform'
	23: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	22: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
	21: from /Users/vwoo/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	20: from /Users/vwoo/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	19: from /Users/vwoo/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	18: from /Users/vwoo/.gem/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	17: from /Users/vwoo/coderpad.io/config/environment.rb:5:in `<top (required)>'
	16: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	15: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	14: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	13: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	12: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	11: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	10: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	 9: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 8: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 7: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 6: from /Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	 5: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	 4: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	 3: from /Users/vwoo/.gem/ruby/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	 2: from /Users/vwoo/.gem/ruby/2.5.0/gems/webpacker-3.5.5/lib/webpacker/railtie.rb:51:in `block in <class:Engine>'
	 1: from /Users/vwoo/.gem/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:76:in `insert'
/Users/vwoo/.gem/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/stack.rb:76:in `insert': can't modify frozen Array (FrozenError)
```

This seems related to the middleware problems recently.

**Comment by vincentwoo** [comment]
This is perhaps related to webpacker? https://github.com/rails/webpacker/issues/1700

**Comment by mshibuya** [comment]
Dup of #3060.
