### ISSUE TITLE
Rails without sass (with sass-rails 6.0.0.beta3 which is a sassc-rails wrapper) not working due to require sass

### ISSUE THREAD

**Issue by glebtv** [sferik/rails_admin#3129]
https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/bootstrap-sass/sass_functions.rb#L1

This line makes it fail:
```
LoadError: cannot load such file -- sass
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /home/gleb/.gem/ruby/2.6.0/gems/rails_admin-1.4.2/lib/rails_admin/bootstrap-sass/sass_functions.rb:1:in `<top (required)>'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
  /home/gleb/.gem/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
  /home/gleb/.gem/ruby/2.6.0/gems/rails_admin-1.4.2/lib/rails_admin/bootstrap-sass.rb:11:in `load!'
```

**Comment by mshibuya** [comment]
https://github.com/sferik/rails_admin/commit/e9a7ad6bba6bae2cfc4d8f7622b8b8eaf48346c3 should work, please give it a try.
