### ISSUE TITLE
There was an error while trying to load the gem 'rails_admin'. when running rspec

### ISSUE THREAD

**Issue by JulienCorb** [sferik/rails_admin#3141]
I'm trying to use rspec in my project that uses rails_admin. 

when I run `bundle exec rspec` I get the following error: 

```
An error occurred while loading ./spec/model_spec/user_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

Bundler::GemRequireError:
  There was an error while trying to load the gem 'rails_admin'.
  Gem Load Error is: uninitialized constant RailsAdmin::Config::Actions::Base
  Backtrace for gem load error is:
  /Users/juliencorbin/TKM_2_1/lib/rails_admin.rb:4:in `<module:Actions>'
  /Users/juliencorbin/TKM_2_1/lib/rails_admin.rb:3:in `<module:Config>'
  /Users/juliencorbin/TKM_2_1/lib/rails_admin.rb:2:in `<module:RailsAdmin>'
  /Users/juliencorbin/TKM_2_1/lib/rails_admin.rb:1:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
  /Users/juliencorbin/TKM_2_1/config/application.rb:17:in `<top (required)>'
  /Users/juliencorbin/TKM_2_1/config/environment.rb:2:in `require_relative'
  /Users/juliencorbin/TKM_2_1/config/environment.rb:2:in `<top (required)>'
  /Users/juliencorbin/TKM_2_1/spec/rails_helper.rb:4:in `require'
  /Users/juliencorbin/TKM_2_1/spec/rails_helper.rb:4:in `<top (required)>'
  /Users/juliencorbin/TKM_2_1/spec/model_spec/user_spec.rb:1:in `require'
  /Users/juliencorbin/TKM_2_1/spec/model_spec/user_spec.rb:1:in `<top (required)>'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in `load'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in `load_file_handling_errors'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in `block in load_spec_files'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `each'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `load_spec_files'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in `setup'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in `run'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
  /usr/local/Cellar/rbenv/1.1.1/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.4/bin/rspec:22:in `load'
  /usr/local/opt/rbenv/versions/2.3.4/bin/rspec:22:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  /usr/local/opt/rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
  ./bin/bundle:3:in `load'
  ./bin/bundle:3:in `<main>'
  Bundler Error Backtrace:
# ./config/application.rb:17:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/model_spec/user_spec.rb:1:in `require'
# ./spec/model_spec/user_spec.rb:1:in `<top (required)>'
# ------------------
# --- Caused by: ---
# NameError:
#   uninitialized constant RailsAdmin::Config::Actions::Base
#   ./lib/rails_admin.rb:4:in `<module:Actions>'
No examples found.

Finished in 0.00036 seconds (files took 3.98 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

The only source I can find is this [guy who has the exact same issue and asked it on SO](https://stackoverflow.com/questions/52539250/rspec-rails-admin-testing-custom-rails-admin-action-in-lib-gives-error) 
but did get any solution. 

Also #2714 could be the same problem but again, no solution. 

Where can it come from ? 

here is my initializers/rails_admin.rb: 

```
require 'rails_admin/config/fields/base'

module RailsAdmin
  module Config
    module Fields
      module Types
        class Datetime < RailsAdmin::Config::Fields::Base

           def value
             value_in_default_time_zone = bindings[:object].send(name)
             return nil if value_in_default_time_zone.nil?
             pacific_time_zone = ActiveSupport::TimeZone.new('London')
             value_in_default_time_zone.in_time_zone(pacific_time_zone)
           end
         end
       end
     end
   end
end

RailsAdmin.config do |config|
   require Rails.root.join('lib', 'rails_admin.rb') #see rais_admin dashboard customization tutorial

# Users
  config.model 'User' do
    list do
      field :id
      field :first_name
      field :last_name
      field :is_subscribed
      field :created_at
      field :special_offer
      field :company
    end
    object_label_method do
      :custom_user_label_method
    end
  end

  def custom_user_label_method
    "#{self.first_name} #{self.last_name} - #{self.id}"
  end


  # Restaurants
  config.model 'Restaurant' do
    object_label_method do
      :custom_restaurant_label_method
    end
  end

  def custom_restaurant_label_method
    "#{self.name} - #{self.id}"
  end

# Meals

  config.model 'Meal' do
    list do
      field :id
      field :restaurant
      field :name
      field :week_day
      field :original_price
      field :no_fees_price
      field :fees
      field :total_price
      field :description
      field :ingredients
      field :allergenes
      field :photo
    end
  end

  # Orders
  config.model Order do
    list do
      field :id
      field :meal
      field :restaurant do
        filterable true
        searchable :name
      end
      field :user do
        searchable [:first_name, :last_name]
      end
      field :pick_up_time
      field :status
      field :created_at
      field :total_price
      field :amount_off
    end
  end

  # Review

  # Meals

    config.model 'Review' do
      list do
        field :id
        field :restaurant
        field :meal
        field :user
        field :rating
        field :comment
        field :created_at
      end
    end

  ### Popular gems integration

  ## == Devise ==
  config.authenticate_with do
    warden.authenticate! scope: :user
  end
  config.current_user_method(&:current_user)

  config.authorize_with do
    redirect_to main_app.root_path unless current_user.is_admin
  end

  ## == Cancan ==
  # config.authorize_with :cancan

  ## == Pundit ==
  # config.authorize_with :pundit

  ## == PaperTrail ==
  # config.audit_with :paper_trail, 'User', 'PaperTrail::Version' # PaperTrail >= 3.0.0

  ### More at https://github.com/sferik/rails_admin/wiki/Base-configuration

  ## == Gravatar integration ==
  ## To disable Gravatar integration in Navigation Bar set to false
  # config.show_gravatar = true

  config.actions do
    dashboard do
      statistics false
    end
    # collection actions
    index                         # mandatory
    new
    export
    history_index
    bulk_delete
    # member actions
    show
    edit
    delete
    history_show
    show_in_app
  end
end


```

and my lib/rails_admin.rb : 

```
module RailsAdmin
    module Config
      module Actions
        class Dashboard < RailsAdmin::Config::Actions::Base
          RailsAdmin::Config::Actions.register(self)

          register_instance_option :root? do
            true
          end

          register_instance_option :breadcrumb_parent do
            nil
          end

          register_instance_option :controller do
            proc do
              #You can specify instance variables
              if Time.now.hour < 15
                @orders = Order.where("created_at >= :start_time and status is null", start_time: DateTime.new(Date.today.year, Date.today.month, Date.today.day, 13,0,0).in_time_zone('Paris').prev_day)
              else
                @orders = Order.where("created_at >= :start_time and status is null", start_time: DateTime.new(Date.today.year, Date.today.month, Date.today.day, 13,0,0).in_time_zone('Paris'))
              end

              @new_users = User.where("created_at >= :last_twentyfour", last_twentyfour: DateTime.now.yesterday)

              @restaurant_emails = Ahoy::Message.where("sent_at >= :eleven", eleven: DateTime.new(Date.today.year, Date.today.month, Date.today.day, 9,0,0).in_time_zone('Paris'))
              #You can access submitted params (just submit your form to the dashboard).
              # if params[:xyz]
              #   @do_something = "here"
              # end

              #You can specify flash messages
              #flash.now[:danger] = "Some type of danger message here."

              #After you're done processing everything, render the new dashboard
              render @action.template_name, status: 200
            end
          end

          register_instance_option :route_fragment do
            ''
          end

          register_instance_option :link_icon do
            'icon-home'
          end

          register_instance_option :statistics? do
            true
          end
        end
      end
    end
  end

```

**Comment by mshibuya** [comment]
Put `require 'rails_admin/config/actions/base` before the class definition `RailsAdmin::Config::Actions::Dashboard`.

**Comment by JulienCorb** [comment]
Hi @mshibuya , 

Where Can I find `RailsAdmin::Config::Actions::Dashboard`, I do not see it in my code; 

I actually found a working solution although I have no clue why this works: 

instead of having `lib/rails_admin.rb`, I created a config subfolder and an actions subfolder in it, then placed my `rails_admin.rb` file inside.

I ended up with the following tree : `lib/config/actions/rails_admin.rb`. You also need to change the path of this file in your `config/initializers/rails_admin.rb` :

In my case I had `require Rails.root.join('lib', 'rails_admin.rb')` and changed it to require `Rails.root.join('lib', 'config', 'actions', 'rails_admin.rb')`.

Then to run `bundle exec rspec` works as expected.

**Comment by mshibuya** [comment]
Your

```ruby
module RailsAdmin
    module Config
      module Actions
        class Dashboard < RailsAdmin::Config::Actions::Base
```

becomes RailsAdmin::Config::Actions::Dashboard.

It's good to hear that you solved this already. It's always a good thing to post follow-up for the issue, since it will help other people having issues similar to yours 😉
