### ISSUE TITLE
undefined method `binary_params_for?' for RailsAdmin::MainController:Class

### ISSUE THREAD

**Issue by sehgalmayank001** [sferik/rails_admin#3286]
Hi
I am getting the above error with a normal rails 6 app,
``` ruby
NoMethodError (undefined method `binary_params_for?' for RailsAdmin::MainController:Class):
  
actionpack (6.0.3.1) lib/action_dispatch/http/parameters.rb:100:in `binary_params_for?'
actionpack (6.0.3.1) lib/action_dispatch/http/parameters.rb:91:in `set_binary_encoding'
actionpack (6.0.3.1) lib/action_dispatch/http/parameters.rb:69:in `path_parameters='
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:47:in `block in serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.3.1) lib/rails/engine.rb:527:in `call'
railties (6.0.3.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.3.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.3.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.3.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
webpacker (4.2.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.1) lib/rails/engine.rb:527:in `call'
puma (4.3.0) lib/puma/configuration.rb:228:in `call'
puma (4.3.0) lib/puma/server.rb:667:in `handle_request'
puma (4.3.0) lib/puma/server.rb:470:in `process_client'
puma (4.3.0) lib/puma/server.rb:328:in `block in run'
puma (4.3.0) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

my rails_admin config file is as follows

``` ruby

RailsAdmin.config do |config|
  config.authenticate_with do
    warden.authenticate!(:database_authenticatable, scope: :admin)
  end
  config.parent_controller = '::ApplicationController'
  config.current_user_method(&:current_admin)
  config.authorize_with :pundit
  # config.label_methods.unshift(:rails_admin_display_name)
  # config.parent_controller = '::ActionController::Base'

  config.actions do
    dashboard                     # mandatory
    index                         # mandatory
    new
    export
    bulk_delete
    show
    edit
    delete

  end
end

class RailsAdmin::ApplicationController
  def policy_scope(scope)
    super([:admin, scope])
  end
end

module RailsAdmin
  module Extensions
    module Pundit
      class AuthorizationAdapter
        def initialize(controller)
          @controller = controller
          @controller.class.send(:alias_method, :pundit_user, :_current_user)
        end

        private

          def policy(record)
            admin_record = [:admin, record]
            if record != nil
              @controller.send(:policy, admin_record)
            else
              ::NilClassPolicy.new(@controller.send(:_current_user), record)
            end
          rescue ::Pundit::NotDefinedError
            Admin::BasePolicy.new(@controller.send(:_current_user), admin_record)
          end
      end
    end
  end
end

```

My parent controller is `::ApplicationController` tried with `::ActionController::Base` but still got the same result.

**Comment by Moltenhead** [comment]
Getting the same any time you try to overload `class RailsAdmin::MainController`.
I suppose some methods are not present the moment you call the overload - caused by the meta programming essence of the project. The overloading must be failing to get the injected methods and breaks on build.
No prrof but that's what tells my intuition.
