### ISSUE TITLE
Error when used with rails --api

### ISSUE THREAD

**Issue by kassi** [sferik/rails_admin#3361]
I create a ruby 3.0.1, rails 6.1.3.2 API application and read that rails_admin should also work with api only apps.

However, as soon as I add `gem "rails_admin"` to the `Gemfile` and `bundle install`, I get the following error when I try to run `rails generate` (without anything specified).

```
/usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:106:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server

For more information see: https://github.com/rails/sprockets/blob/070fc01947c111d35bb4c836e9bb71962a8e0595/UPGRADING.md#manifestjs (Sprockets::Railtie::ManifestNeededError)
	from /usr/local/bundle/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
	from /app/config/environment.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
	from /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:106:in `preload'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

I couldn't find  and hints in the doc on how to use it with an API only rails app.

**Comment by mshibuya** [comment]
Just follow the instruction given in the error message.
